<a href="https://colab.research.google.com/github/wjlee611/studyPython_Library/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.4.0'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1], 
                index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [8]:
s['c']

0.5

In [9]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s

True

In [11]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
                index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [12]:
s[4]

0.25

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
dtype: int64

In [16]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시': 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 1471040,
            '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [20]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5, 5),
            columns=['A', 'B', 'C', 'D', 'E'],
            index=[1, 2, 3, 4, 5])

A         B         C         D         E
1  0.715439  0.125044  0.445005  0.710151  0.418181
2  0.432967  0.150430  0.926545  0.925497  0.833073
3  0.999778  0.393301  0.261366  0.727314  0.262056
4  0.294839  0.084480  0.045280  0.121321  0.307170
5  0.779219  0.012320  0.700324  0.374114  0.293685

In [22]:
male_tuple = {'서울특별시': 4732275,
            '부산광역시': 1668618,
            '인천광역시': 1476813,
            '대구광역시': 1198815,
            '대전광역시': 734441,
            '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시': 4988571,
            '부산광역시': 1735805,
            '인천광역시': 1470404,
            '대구광역시': 1229139,
            '대전광역시': 736599,
            '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수': population,
                        '남자인구수': male,
                        '여자인구수': female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [26]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [27]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [28]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [29]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [30]:
idx[1]

4

In [31]:
idx[0:5:2]

Int64Index([2, 6, 10], dtype='int64')

In [32]:
idx[-1::]

Int64Index([10], dtype='int64')

In [33]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [34]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [35]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])

print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(2))
print(idx1 ^ idx2)

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_1432/1047857996.py:8: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  print(idx1 & idx2)
/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_1432/1047857996.py:10: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  print(idx1 | idx2)
/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_1432/1047857996.py:13: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  print(idx1 ^ idx2)




---



## 인덱싱(Indexing)

In [36]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
            index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [37]:
s['b']

0.25

In [38]:
'b' in s

True

In [39]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [41]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [42]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [45]:
s[(['a', 'c', 'e'])]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [46]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
            index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [47]:
s[1]

'a'

In [48]:
s[2:4]

5    c
7    d
dtype: object

In [49]:
s.iloc[1]

'b'

In [50]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [51]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [52]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [53]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [54]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [55]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [57]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [58]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [59]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [60]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [61]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [62]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [63]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [64]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [65]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [66]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [67]:
korea_df.loc[(korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 < 100)]

인구수    남자인구수    여자인구수       남여비율
서울특별시  9720846  4732275  4988571  94.862336
부산광역시  3404423  1668618  1735805  96.129346

In [69]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [70]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [71]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
            ('부산광역시', 2010), ('부산광역시', 2020),
            ('인천광역시', 2010), ('인천광역시', 2020),
            ('대구광역시', 2010), ('대구광역시', 2020),
            ('대전광역시', 2010), ('대전광역시', 2020),
            ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [72]:
pop_tuples = [10312545, 9720846,
            2567910, 3404423,
            2758296, 2947217,
            2511676, 2427954,
            1503664, 1471040,
            1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [73]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [74]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [75]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [76]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [77]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [78]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [79]:
male_tuple = [5111259, 4732275,
            1773170, 1668618,
            1390356, 1476813,
            1255245, 1198815,
            753648, 734441,
            721780, 720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [80]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [81]:
female_tuple = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856, 734988]
female_tuple

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [82]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple,
                        '여자인구수': female_tuple})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [83]:
ratio = korea_mdf['남자인구수'] / korea_mdf.여자인구수 * 100
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [84]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [85]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple,
                        '여자인구수': female_tuple,
                        '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [86]:
df = pd.DataFrame(np.random.rand(6, 3),
                index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.892791  0.536852  0.166509
  2  0.131916  0.636416  0.900880
b 1  0.586406  0.693499  0.331019
  2  0.492022  0.577362  0.588606
c 1  0.028666  0.885600  0.911865
  2  0.572206  0.375872  0.318132

In [87]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [88]:
pd.MultiIndex.from_tuples([('a', 1),
                        ('a', 2),
                        ('b', 1),
                        ('b', 2),
                        ('c', 1),
                        ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
pd.MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
            codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [93]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [95]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      0.24  0.51  0.83  0.48  0.48  0.50
      2     -1.10  0.66 -0.72 -0.12 -2.37 -1.16
b     1     -0.01 -0.22 -0.81  0.39 -0.07 -0.93
      2      0.09 -0.21  1.92 -0.64 -0.30 -0.72
c     1     -0.96  1.24 -0.12  0.28 -1.51 -1.52
      2     -0.93  0.23  0.86 -0.18 -1.55  0.34

In [96]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1      0.83  0.48
      2     -0.72 -0.12
b     1     -0.81  0.39
      2      1.92 -0.64
c     1     -0.12  0.28
      2      0.86 -0.18

#### 인덱싱 및 슬라이싱

In [97]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [98]:
population['인천광역시', 2010]

2758296

In [99]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [100]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [102]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [103]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      0.24  0.51  0.83  0.48  0.48  0.50
      2     -1.10  0.66 -0.72 -0.12 -2.37 -1.16
b     1     -0.01 -0.22 -0.81  0.39 -0.07 -0.93
      2      0.09 -0.21  1.92 -0.64 -0.30 -0.72
c     1     -0.96  1.24 -0.12  0.28 -1.51 -1.52
      2     -0.93  0.23  0.86 -0.18 -1.55  0.34

In [104]:
mdf['c2', 1]

name1  name2
a      1        0.83
       2       -0.72
b      1       -0.81
       2        1.92
c      1       -0.12
       2        0.86
Name: (c2, 1), dtype: float64

In [105]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1      0.24  0.51  0.83  0.48
      2     -1.10  0.66 -0.72 -0.12
b     1     -0.01 -0.22 -0.81  0.39

In [106]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1        0.83
       2       -0.72
b      1       -0.81
       2        1.92
c      1       -0.12
       2        0.86
Name: (c2, 1), dtype: float64

In [107]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      0.66 -0.12 -1.16
b     2     -0.21 -0.64 -0.72
c     2      0.23 -0.18  0.34

#### 다중 인덱스 재정렬

In [108]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [109]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [112]:
#korea_mdf['서울특별시':'인천광역시']

korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [113]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [114]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [115]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [117]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [118]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [120]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [121]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [122]:
idx_flat.set_index('행정구역', '년도')

/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_1432/1791047165.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only.
  idx_flat.set_index('행정구역', '년도')


년도      총인구수    남자인구수    여자인구수        남여비율
행정구역                                               
광주광역시  2010   1454636   721780   732856   98.488653
광주광역시  2020   1455048   720060   734988   97.968946
대구광역시  2010   2511676  1255245  1256431   99.905606
대구광역시  2020   2427954  1198815  1229139   97.532907
대전광역시  2010   1503664   753648   750016  100.484256
대전광역시  2020   1471040   734441   736599   99.707032
부산광역시  2010   2567910  1773170  1794740   98.798155
부산광역시  2020   3404423  1668618  1735805   96.129346
서울특별시  2010  10312545  5111259  5201286   98.269140
서울특별시  2020   9720846  4732275  4988571   94.862336
인천광역시  2010   2758296  1390356  1367940  101.638668
인천광역시  2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [124]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    5
1    9
2    4
3    1
4    9
dtype: int64

In [125]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                columns=['A', 'B', 'C'])
df

A  B  C
0  0  9  1
1  0  0  3
2  2  8  6

In [127]:
np.exp(s)

0     148.413159
1    8103.083928
2      54.598150
3       2.718282
4    8103.083928
dtype: float64

In [128]:
np.cos(df * np.pi / 4)

A         B             C
0  1.000000e+00  0.707107  7.071068e-01
1  1.000000e+00  1.000000 -7.071068e-01
2  6.123234e-17  1.000000 -1.836970e-16

In [129]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [130]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [132]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                columns=list('ACD'))
df1

A   C   D
0   4   0  19
1   9   4  12
2  16  12  18

In [133]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                columns=list('BAECD'))
df2

B   A   E   C   D
0   6  12  13  16  17
1   9  12   2  17   6
2  12   3   2   8  14
3   9  18  10   4  11
4  17   3   5   5  11

In [134]:
df1 + df2

A   B     C     D   E
0  16.0 NaN  16.0  36.0 NaN
1  21.0 NaN  21.0  18.0 NaN
2  19.0 NaN  20.0  32.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [139]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  16.000000  16.444444  16.000000  36.000000  23.444444
1  21.000000  19.444444  21.000000  18.000000  12.444444
2  19.000000  22.444444  20.000000  32.000000  12.444444
3  28.444444  19.444444  14.444444  21.444444  20.444444
4  13.444444  27.444444  15.444444  21.444444  15.444444

### 연산자 범용 함수


#### add()

In [140]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[4, 3, 7],
       [5, 6, 2],
       [2, 8, 6]])

In [141]:
a + a[0]

array([[ 8,  6, 14],
       [ 9,  9,  9],
       [ 6, 11, 13]])

In [143]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  4  3  7
1  5  6  2
2  2  8  6

In [144]:
df + df.iloc[0]

A   B   C
0  8   6  14
1  9   9   9
2  6  11  13

In [145]:
df.add(df.iloc[0])

A   B   C
0  8   6  14
1  9   9   9
2  6  11  13

#### sub() / subtract()

In [147]:
a

array([[4, 3, 7],
       [5, 6, 2],
       [2, 8, 6]])

In [148]:
a - a[0]

array([[ 0,  0,  0],
       [ 1,  3, -5],
       [-2,  5, -1]])

In [149]:
df

A  B  C
0  4  3  7
1  5  6  2
2  2  8  6

In [150]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  1  3 -5
2 -2  5 -1

In [151]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  1  3 -5
2 -2  5 -1

In [154]:
df.subtract(df['B'], axis=0)

A  B  C
0  1  0  4
1 -1  0 -4
2 -6  0 -2

#### mul() / multply()




In [155]:
a

array([[4, 3, 7],
       [5, 6, 2],
       [2, 8, 6]])

In [158]:
a * a[1]

array([[20, 18, 14],
       [25, 36,  4],
       [10, 48, 12]])

In [157]:
df

A  B  C
0  4  3  7
1  5  6  2
2  2  8  6

In [159]:
df * df.iloc[1]

A   B   C
0  20  18  14
1  25  36   4
2  10  48  12

In [160]:
df.mul(df.iloc[1])

A   B   C
0  20  18  14
1  25  36   4
2  10  48  12

In [161]:
df.multiply(df.iloc[2])

A   B   C
0   8  24  42
1  10  48  12
2   4  64  36

#### truediv() /  div() / divide() / floordiv()

In [162]:
a

array([[4, 3, 7],
       [5, 6, 2],
       [2, 8, 6]])

In [163]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.25      , 2.        , 0.28571429],
       [0.5       , 2.66666667, 0.85714286]])

In [164]:
df

A  B  C
0  4  3  7
1  5  6  2
2  2  8  6

In [165]:
df / df.iloc[0]

A         B         C
0  1.00  1.000000  1.000000
1  1.25  2.000000  0.285714
2  0.50  2.666667  0.857143

In [166]:
df.truediv(df.iloc[0])

A         B         C
0  1.00  1.000000  1.000000
1  1.25  2.000000  0.285714
2  0.50  2.666667  0.857143

In [167]:
df.div(df.iloc[1])

A         B    C
0  0.8  0.500000  3.5
1  1.0  1.000000  1.0
2  0.4  1.333333  3.0

In [168]:
df.divide(df.iloc[2])

A      B         C
0  2.0  0.375  1.166667
1  2.5  0.750  0.333333
2  1.0  1.000  1.000000

In [169]:
a // a[0]

array([[1, 1, 1],
       [1, 2, 0],
       [0, 2, 0]])

In [170]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  2  0
2  0  2  0

#### mod()

In [171]:
a

array([[4, 3, 7],
       [5, 6, 2],
       [2, 8, 6]])

In [172]:
a % a[0]

array([[0, 0, 0],
       [1, 0, 2],
       [2, 2, 6]])

In [173]:
df

A  B  C
0  4  3  7
1  5  6  2
2  2  8  6

In [175]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  0  2
2  2  2  6

#### pow()

In [177]:
a

array([[4, 3, 7],
       [5, 6, 2],
       [2, 8, 6]])

In [178]:
a ** a[0]

array([[   256,     27, 823543],
       [   625,    216,    128],
       [    16,    512, 279936]])

In [179]:
df

A  B  C
0  4  3  7
1  5  6  2
2  2  8  6

In [180]:
df.pow(df.iloc[0])

A    B       C
0  256   27  823543
1  625  216     128
2   16  512  279936

In [181]:
row = df.iloc[0, ::2]
row

A    4
C    7
Name: 0, dtype: int64

In [182]:
df - row

A   B    C
0  0.0 NaN  0.0
1  1.0 NaN -5.0
2 -2.0 NaN -1.0

### 정렬(Sort)

In [183]:
s = pd.Series(range(5), index=list('ADBCE'))
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [184]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [185]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [186]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                                    index=[2, 4, 1, 3],
                                    columns=list('BDAC'))
df

B  D  A  C
2  8  0  4  5
4  3  6  5  8
1  0  2  6  9
3  6  2  0  0

In [187]:
df.sort_index()

B  D  A  C
1  0  2  6  9
2  8  0  4  5
3  6  2  0  0
4  3  6  5  8

In [190]:
df.sort_index(axis=1)

A  B  C  D
2  4  8  5  0
4  5  3  8  6
1  6  0  9  2
3  0  6  0  2

In [188]:
df.sort_values(by='A')

B  D  A  C
3  6  2  0  0
2  8  0  4  5
4  3  6  5  8
1  0  2  6  9

In [189]:
df.sort_values(by=['A', 'C'])

B  D  A  C
3  6  2  0  0
2  8  0  4  5
4  3  6  5  8
1  0  2  6  9

### 순위(Ranking)


In [191]:
s = pd.Series([-2, 4, 5, 7, 2, -1, 4, 9, 4, -1])
s

0   -2
1    4
2    5
3    7
4    2
5   -1
6    4
7    9
8    4
9   -1
dtype: int64

In [192]:
s.rank()

0     1.0
1     6.0
2     8.0
3     9.0
4     4.0
5     2.5
6     6.0
7    10.0
8     6.0
9     2.5
dtype: float64

In [193]:
s.rank(method='first')

0     1.0
1     5.0
2     8.0
3     9.0
4     4.0
5     2.0
6     6.0
7    10.0
8     7.0
9     3.0
dtype: float64

In [195]:
s.rank(method='min')

0     1.0
1     5.0
2     8.0
3     9.0
4     4.0
5     2.0
6     5.0
7    10.0
8     5.0
9     2.0
dtype: float64

### 고성능 연산

In [196]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [197]:
%timeit df1 + df2 + df3 + df4

24.8 ms ± 723 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [198]:
%timeit pd.eval('df1 + df2 + df3 + df4')

24.7 ms ± 645 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [199]:
%timeit df1 * -df2 / (-df3 * df4)

40.6 ms ± 667 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [201]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

40.4 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [205]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

29.9 ms ± 280 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [206]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

30 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [207]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=list('ABCDE'))
df.head()

A         B         C         D         E
0  0.770606  0.802242  0.814552  0.785926  0.881645
1  0.489708  0.831584  0.512751  0.601841  0.085502
2  0.116476  0.237546  0.160454  0.350938  0.428498
3  0.501728  0.571849  0.986471  0.272332  0.774695
4  0.912626  0.626143  0.312410  0.464759  0.247114

In [211]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

4.88 ms ± 81.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [212]:
%timeit pd.eval("df['A'] + df['B'] / df['C'] - df['D'] * df['E']")

21 ms ± 324 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [214]:
%timeit df.eval('A + B / C - D * E')

6.81 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [215]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.770606  0.802242  0.814552  0.785926  0.881645  1.062586
1  0.489708  0.831584  0.512751  0.601841  0.085502  2.060059
2  0.116476  0.237546  0.160454  0.350938  0.428498  1.446555
3  0.501728  0.571849  0.986471  0.272332  0.774695  0.870446
4  0.912626  0.626143  0.312410  0.464759  0.247114  2.802011

In [216]:
df.eval('R = A - B / C + D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.770606  0.802242  0.814552  0.785926  0.881645  0.478626
1  0.489708  0.831584  0.512751  0.601841  0.085502 -1.080643
2  0.116476  0.237546  0.160454  0.350938  0.428498 -1.213602
3  0.501728  0.571849  0.986471  0.272332  0.774695  0.133010
4  0.912626  0.626143  0.312410  0.464759  0.247114 -0.976759

In [218]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.526206
1         0.729832
2         0.129861
3         1.041742
4         1.177008
            ...   
999995    0.471207
999996    0.965953
999997    0.970485
999998    1.126224
999999   -0.184432
Length: 1000000, dtype: float64

In [219]:
df.eval('A + @col_mean')  #@: 외부 변수 참조

0         1.526206
1         0.729832
2         0.129861
3         1.041742
4         1.177008
            ...   
999995    0.471207
999996    0.965953
999997    0.970485
999998    1.126224
999999   -0.184432
Length: 1000000, dtype: float64

In [220]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C < 0.5)]

A         B         C         D         E         R
2       0.116476  0.237546  0.160454  0.350938  0.428498 -1.213602
10      0.284763  0.490507  0.462547  0.672307  0.637189 -0.347298
13      0.023105  0.149185  0.444869  0.793838  0.804400  0.326322
20      0.206856  0.341135  0.209572  0.623332  0.753807 -0.951044
25      0.222581  0.464322  0.460713  0.688911  0.838969 -0.207277
...          ...       ...       ...       ...       ...       ...
999949  0.208845  0.392386  0.346477  0.912901  0.824760 -0.170733
999964  0.158181  0.379586  0.230161  0.309493  0.971393 -1.190399
999974  0.085048  0.013180  0.477120  0.261001  0.917937  0.297006
999987  0.212159  0.113148  0.274260  0.328503  0.206458 -0.132576
999990  0.389965  0.275384  0.342065  0.278532  0.579564 -0.253672

[124606 rows x 6 columns]

In [221]:
pd.eval("df[(df.A < 0.5) & (df.B < 0.5) & (df.C < 0.5)]")

A         B         C         D         E         R
2       0.116476  0.237546  0.160454  0.350938  0.428498 -1.213602
10      0.284763  0.490507  0.462547  0.672307  0.637189 -0.347298
13      0.023105  0.149185  0.444869  0.793838  0.804400  0.326322
20      0.206856  0.341135  0.209572  0.623332  0.753807 -0.951044
25      0.222581  0.464322  0.460713  0.688911  0.838969 -0.207277
...          ...       ...       ...       ...       ...       ...
999949  0.208845  0.392386  0.346477  0.912901  0.824760 -0.170733
999964  0.158181  0.379586  0.230161  0.309493  0.971393 -1.190399
999974  0.085048  0.013180  0.477120  0.261001  0.917937  0.297006
999987  0.212159  0.113148  0.274260  0.328503  0.206458 -0.132576
999990  0.389965  0.275384  0.342065  0.278532  0.579564 -0.253672

[124606 rows x 6 columns]

In [229]:
df.query("(A < 0.5) and (B < 0.5) and (C < 0.5)")

A         B         C         D         E         R
2       0.116476  0.237546  0.160454  0.350938  0.428498 -1.213602
10      0.284763  0.490507  0.462547  0.672307  0.637189 -0.347298
13      0.023105  0.149185  0.444869  0.793838  0.804400  0.326322
20      0.206856  0.341135  0.209572  0.623332  0.753807 -0.951044
25      0.222581  0.464322  0.460713  0.688911  0.838969 -0.207277
...          ...       ...       ...       ...       ...       ...
999949  0.208845  0.392386  0.346477  0.912901  0.824760 -0.170733
999964  0.158181  0.379586  0.230161  0.309493  0.971393 -1.190399
999974  0.085048  0.013180  0.477120  0.261001  0.917937  0.297006
999987  0.212159  0.113148  0.274260  0.328503  0.206458 -0.132576
999990  0.389965  0.275384  0.342065  0.278532  0.579564 -0.253672

[124606 rows x 6 columns]

In [230]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B <col_mean)]

A         B         C         D         E         R
2       0.116476  0.237546  0.160454  0.350938  0.428498 -1.213602
8       0.422038  0.483233  0.811753  0.535638  0.484781  0.086410
10      0.284763  0.490507  0.462547  0.672307  0.637189 -0.347298
11      0.183989  0.288123  0.947068  0.936342  0.452223  0.303198
13      0.023105  0.149185  0.444869  0.793838  0.804400  0.326322
...          ...       ...       ...       ...       ...       ...
999974  0.085048  0.013180  0.477120  0.261001  0.917937  0.297006
999976  0.098092  0.140211  0.926912  0.658834  0.159282  0.051766
999985  0.284290  0.220031  0.897507  0.244379  0.432985  0.144945
999987  0.212159  0.113148  0.274260  0.328503  0.206458 -0.132576
999990  0.389965  0.275384  0.342065  0.278532  0.579564 -0.253672

[250090 rows x 6 columns]

In [231]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
2       0.116476  0.237546  0.160454  0.350938  0.428498 -1.213602
8       0.422038  0.483233  0.811753  0.535638  0.484781  0.086410
10      0.284763  0.490507  0.462547  0.672307  0.637189 -0.347298
11      0.183989  0.288123  0.947068  0.936342  0.452223  0.303198
13      0.023105  0.149185  0.444869  0.793838  0.804400  0.326322
...          ...       ...       ...       ...       ...       ...
999974  0.085048  0.013180  0.477120  0.261001  0.917937  0.297006
999976  0.098092  0.140211  0.926912  0.658834  0.159282  0.051766
999985  0.284290  0.220031  0.897507  0.244379  0.432985  0.144945
999987  0.212159  0.113148  0.274260  0.328503  0.206458 -0.132576
999990  0.389965  0.275384  0.342065  0.278532  0.579564 -0.253672

[250090 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [232]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly