<a href="https://colab.research.google.com/github/wjlee611/studyPython_Library/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.4.0'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1], 
                index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [8]:
s['c']

0.5

In [9]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s

True

In [11]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
                index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [12]:
s[4]

0.25

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
dtype: int64

In [16]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시': 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 1471040,
            '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [20]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5, 5),
            columns=['A', 'B', 'C', 'D', 'E'],
            index=[1, 2, 3, 4, 5])

A         B         C         D         E
1  0.077925  0.956297  0.989688  0.621121  0.046146
2  0.572040  0.434779  0.887183  0.522791  0.447793
3  0.623605  0.893348  0.125393  0.933547  0.140195
4  0.848026  0.649063  0.572306  0.510506  0.718981
5  0.967718  0.981716  0.065777  0.927243  0.501828

In [22]:
male_tuple = {'서울특별시': 4732275,
            '부산광역시': 1668618,
            '인천광역시': 1476813,
            '대구광역시': 1198815,
            '대전광역시': 734441,
            '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시': 4988571,
            '부산광역시': 1735805,
            '인천광역시': 1470404,
            '대구광역시': 1229139,
            '대전광역시': 736599,
            '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수': population,
                        '남자인구수': male,
                        '여자인구수': female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [26]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [27]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [28]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [29]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [30]:
idx[1]

4

In [31]:
idx[0:5:2]

Int64Index([2, 6, 10], dtype='int64')

In [32]:
idx[-1::]

Int64Index([10], dtype='int64')

In [33]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [34]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [35]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])

print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(2))
print(idx1 ^ idx2)

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_8645/1047857996.py:8: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  print(idx1 & idx2)
/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_8645/1047857996.py:10: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  print(idx1 | idx2)
/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_8645/1047857996.py:13: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  print(idx1 ^ idx2)




---



## 인덱싱(Indexing)

In [36]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
            index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [37]:
s['b']

0.25

In [38]:
'b' in s

True

In [39]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [41]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [42]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [45]:
s[(['a', 'c', 'e'])]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [46]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
            index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [47]:
s[1]

'a'

In [48]:
s[2:4]

5    c
7    d
dtype: object

In [49]:
s.iloc[1]

'b'

In [50]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [51]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [52]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [53]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [54]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [55]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [57]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [58]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [59]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [60]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [61]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [62]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [63]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [64]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [65]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [66]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [67]:
korea_df.loc[(korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 < 100)]

인구수    남자인구수    여자인구수       남여비율
서울특별시  9720846  4732275  4988571  94.862336
부산광역시  3404423  1668618  1735805  96.129346

In [69]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [70]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [71]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
            ('부산광역시', 2010), ('부산광역시', 2020),
            ('인천광역시', 2010), ('인천광역시', 2020),
            ('대구광역시', 2010), ('대구광역시', 2020),
            ('대전광역시', 2010), ('대전광역시', 2020),
            ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [72]:
pop_tuples = [10312545, 9720846,
            2567910, 3404423,
            2758296, 2947217,
            2511676, 2427954,
            1503664, 1471040,
            1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [73]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [74]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [75]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [76]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [77]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [78]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [79]:
male_tuple = [5111259, 4732275,
            1773170, 1668618,
            1390356, 1476813,
            1255245, 1198815,
            753648, 734441,
            721780, 720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [80]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [81]:
female_tuple = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856, 734988]
female_tuple

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [82]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple,
                        '여자인구수': female_tuple})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [83]:
ratio = korea_mdf['남자인구수'] / korea_mdf.여자인구수 * 100
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [84]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [85]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple,
                        '여자인구수': female_tuple,
                        '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [86]:
df = pd.DataFrame(np.random.rand(6, 3),
                index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.333078  0.085981  0.376185
  2  0.854480  0.572666  0.170884
b 1  0.857085  0.723146  0.615302
  2  0.344443  0.801254  0.455351
c 1  0.674041  0.212491  0.251368
  2  0.680564  0.114864  0.074996

In [87]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [88]:
pd.MultiIndex.from_tuples([('a', 1),
                        ('a', 2),
                        ('b', 1),
                        ('b', 2),
                        ('c', 1),
                        ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
pd.MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
            codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [92]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [93]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.31  0.43 -0.39 -0.58  1.37 -1.06
      2      0.78  1.12  0.85  1.06 -0.63  0.14
b     1      1.14  1.92  0.31  0.87  0.37  1.12
      2     -0.05  0.18 -1.49 -1.24  0.87 -0.87
c     1      0.15  1.77 -0.46 -1.57  1.08 -0.43
      2     -0.02 -0.85 -0.26  1.07 -0.81 -0.05

In [94]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.39 -0.58
      2      0.85  1.06
b     1      0.31  0.87
      2     -1.49 -1.24
c     1     -0.46 -1.57
      2     -0.26  1.07

#### 인덱싱 및 슬라이싱

In [95]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [96]:
population['인천광역시', 2010]

2758296

In [97]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [98]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [99]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [100]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.31  0.43 -0.39 -0.58  1.37 -1.06
      2      0.78  1.12  0.85  1.06 -0.63  0.14
b     1      1.14  1.92  0.31  0.87  0.37  1.12
      2     -0.05  0.18 -1.49 -1.24  0.87 -0.87
c     1      0.15  1.77 -0.46 -1.57  1.08 -0.43
      2     -0.02 -0.85 -0.26  1.07 -0.81 -0.05

In [101]:
mdf['c2', 1]

name1  name2
a      1       -0.39
       2        0.85
b      1        0.31
       2       -1.49
c      1       -0.46
       2       -0.26
Name: (c2, 1), dtype: float64

In [102]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.31  0.43 -0.39 -0.58
      2      0.78  1.12  0.85  1.06
b     1      1.14  1.92  0.31  0.87

In [103]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -0.39
       2        0.85
b      1        0.31
       2       -1.49
c      1       -0.46
       2       -0.26
Name: (c2, 1), dtype: float64

In [104]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      1.12  1.06  0.14
b     2      0.18 -1.24 -0.87
c     2     -0.85  1.07 -0.05

#### 다중 인덱스 재정렬

In [105]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [106]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [107]:
#korea_mdf['서울특별시':'인천광역시']

korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [108]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [109]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [110]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [111]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [112]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [113]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [114]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [115]:
idx_flat.set_index('행정구역', '년도')

/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_8645/1791047165.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only.
  idx_flat.set_index('행정구역', '년도')


년도      총인구수    남자인구수    여자인구수        남여비율
행정구역                                               
광주광역시  2010   1454636   721780   732856   98.488653
광주광역시  2020   1455048   720060   734988   97.968946
대구광역시  2010   2511676  1255245  1256431   99.905606
대구광역시  2020   2427954  1198815  1229139   97.532907
대전광역시  2010   1503664   753648   750016  100.484256
대전광역시  2020   1471040   734441   736599   99.707032
부산광역시  2010   2567910  1773170  1794740   98.798155
부산광역시  2020   3404423  1668618  1735805   96.129346
서울특별시  2010  10312545  5111259  5201286   98.269140
서울특별시  2020   9720846  4732275  4988571   94.862336
인천광역시  2010   2758296  1390356  1367940  101.638668
인천광역시  2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [116]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    2
1    1
2    4
3    8
4    4
dtype: int64

In [117]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                columns=['A', 'B', 'C'])
df

A  B  C
0  6  1  4
1  1  6  9
2  6  7  4

In [118]:
np.exp(s)

0       7.389056
1       2.718282
2      54.598150
3    2980.957987
4      54.598150
dtype: float64

In [119]:
np.cos(df * np.pi / 4)

A             B         C
0 -1.836970e-16  7.071068e-01 -1.000000
1  7.071068e-01 -1.836970e-16  0.707107
2 -1.836970e-16  7.071068e-01 -1.000000

In [120]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [121]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [122]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                columns=list('ACD'))
df1

A   C   D
0   7  16   9
1  12   2   7
2  12  11  11

In [123]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                columns=list('BAECD'))
df2

B   A   E   C   D
0   2   2   7  10  17
1   7  15   0  15  10
2  14   8  15  14  15
3   6   5   0   7   6
4  10   3  11  15  18

In [124]:
df1 + df2

A   B     C     D   E
0   9.0 NaN  26.0  26.0 NaN
1  27.0 NaN  17.0  17.0 NaN
2  20.0 NaN  25.0  26.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [125]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0   9.000000  11.666667  26.000000  26.000000  16.666667
1  27.000000  16.666667  17.000000  17.000000   9.666667
2  20.000000  23.666667  25.000000  26.000000  24.666667
3  14.666667  15.666667  16.666667  15.666667   9.666667
4  12.666667  19.666667  24.666667  27.666667  20.666667

### 연산자 범용 함수


#### add()

In [126]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[2, 6, 4],
       [5, 1, 7],
       [3, 6, 8]])

In [127]:
a + a[0]

array([[ 4, 12,  8],
       [ 7,  7, 11],
       [ 5, 12, 12]])

In [128]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  2  6  4
1  5  1  7
2  3  6  8

In [129]:
df + df.iloc[0]

A   B   C
0  4  12   8
1  7   7  11
2  5  12  12

In [130]:
df.add(df.iloc[0])

A   B   C
0  4  12   8
1  7   7  11
2  5  12  12

#### sub() / subtract()

In [131]:
a

array([[2, 6, 4],
       [5, 1, 7],
       [3, 6, 8]])

In [132]:
a - a[0]

array([[ 0,  0,  0],
       [ 3, -5,  3],
       [ 1,  0,  4]])

In [133]:
df

A  B  C
0  2  6  4
1  5  1  7
2  3  6  8

In [134]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  3 -5  3
2  1  0  4

In [135]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  3 -5  3
2  1  0  4

In [136]:
df.subtract(df['B'], axis=0)

A  B  C
0 -4  0 -2
1  4  0  6
2 -3  0  2

#### mul() / multply()




In [137]:
a

array([[2, 6, 4],
       [5, 1, 7],
       [3, 6, 8]])

In [138]:
a * a[1]

array([[10,  6, 28],
       [25,  1, 49],
       [15,  6, 56]])

In [139]:
df

A  B  C
0  2  6  4
1  5  1  7
2  3  6  8

In [140]:
df * df.iloc[1]

A  B   C
0  10  6  28
1  25  1  49
2  15  6  56

In [141]:
df.mul(df.iloc[1])

A  B   C
0  10  6  28
1  25  1  49
2  15  6  56

In [142]:
df.multiply(df.iloc[2])

A   B   C
0   6  36  32
1  15   6  56
2   9  36  64

#### truediv() /  div() / divide() / floordiv()

In [143]:
a

array([[2, 6, 4],
       [5, 1, 7],
       [3, 6, 8]])

In [144]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [2.5       , 0.16666667, 1.75      ],
       [1.5       , 1.        , 2.        ]])

In [145]:
df

A  B  C
0  2  6  4
1  5  1  7
2  3  6  8

In [146]:
df / df.iloc[0]

A         B     C
0  1.0  1.000000  1.00
1  2.5  0.166667  1.75
2  1.5  1.000000  2.00

In [147]:
df.truediv(df.iloc[0])

A         B     C
0  1.0  1.000000  1.00
1  2.5  0.166667  1.75
2  1.5  1.000000  2.00

In [148]:
df.div(df.iloc[1])

A    B         C
0  0.4  6.0  0.571429
1  1.0  1.0  1.000000
2  0.6  6.0  1.142857

In [149]:
df.divide(df.iloc[2])

A         B      C
0  0.666667  1.000000  0.500
1  1.666667  0.166667  0.875
2  1.000000  1.000000  1.000

In [150]:
a // a[0]

array([[1, 1, 1],
       [2, 0, 1],
       [1, 1, 2]])

In [151]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  2  0  1
2  1  1  2

#### mod()

In [152]:
a

array([[2, 6, 4],
       [5, 1, 7],
       [3, 6, 8]])

In [153]:
a % a[0]

array([[0, 0, 0],
       [1, 1, 3],
       [1, 0, 0]])

In [154]:
df

A  B  C
0  2  6  4
1  5  1  7
2  3  6  8

In [155]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  1  3
2  1  0  0

#### pow()

In [156]:
a

array([[2, 6, 4],
       [5, 1, 7],
       [3, 6, 8]])

In [157]:
a ** a[0]

array([[    4, 46656,   256],
       [   25,     1,  2401],
       [    9, 46656,  4096]])

In [158]:
df

A  B  C
0  2  6  4
1  5  1  7
2  3  6  8

In [159]:
df.pow(df.iloc[0])

A      B     C
0   4  46656   256
1  25      1  2401
2   9  46656  4096

In [160]:
row = df.iloc[0, ::2]
row

A    2
C    4
Name: 0, dtype: int64

In [161]:
df - row

A   B    C
0  0.0 NaN  0.0
1  3.0 NaN  3.0
2  1.0 NaN  4.0

### 정렬(Sort)

In [162]:
s = pd.Series(range(5), index=list('ADBCE'))
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [163]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [164]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [165]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                                    index=[2, 4, 1, 3],
                                    columns=list('BDAC'))
df

B  D  A  C
2  5  8  9  9
4  8  1  3  8
1  3  2  3  3
3  0  9  5  2

In [166]:
df.sort_index()

B  D  A  C
1  3  2  3  3
2  5  8  9  9
3  0  9  5  2
4  8  1  3  8

In [167]:
df.sort_index(axis=1)

A  B  C  D
2  9  5  9  8
4  3  8  8  1
1  3  3  3  2
3  5  0  2  9

In [168]:
df.sort_values(by='A')

B  D  A  C
4  8  1  3  8
1  3  2  3  3
3  0  9  5  2
2  5  8  9  9

In [169]:
df.sort_values(by=['A', 'C'])

B  D  A  C
1  3  2  3  3
4  8  1  3  8
3  0  9  5  2
2  5  8  9  9

### 순위(Ranking)


In [170]:
s = pd.Series([-2, 4, 5, 7, 2, -1, 4, 9, 4, -1])
s

0   -2
1    4
2    5
3    7
4    2
5   -1
6    4
7    9
8    4
9   -1
dtype: int64

In [171]:
s.rank()

0     1.0
1     6.0
2     8.0
3     9.0
4     4.0
5     2.5
6     6.0
7    10.0
8     6.0
9     2.5
dtype: float64

In [172]:
s.rank(method='first')

0     1.0
1     5.0
2     8.0
3     9.0
4     4.0
5     2.0
6     6.0
7    10.0
8     7.0
9     3.0
dtype: float64

In [173]:
s.rank(method='min')

0     1.0
1     5.0
2     8.0
3     9.0
4     4.0
5     2.0
6     5.0
7    10.0
8     5.0
9     2.0
dtype: float64

### 고성능 연산

In [174]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [175]:
%timeit df1 + df2 + df3 + df4

23.2 ms ± 40.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [176]:
%timeit pd.eval('df1 + df2 + df3 + df4')

23.8 ms ± 349 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [177]:
%timeit df1 * -df2 / (-df3 * df4)

38 ms ± 185 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [178]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

38.5 ms ± 54.3 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [179]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

29.1 ms ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [180]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

30.2 ms ± 645 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [181]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=list('ABCDE'))
df.head()

A         B         C         D         E
0  0.781122  0.162240  0.510469  0.432363  0.010421
1  0.837288  0.360168  0.408874  0.055812  0.712574
2  0.342259  0.156306  0.204718  0.372911  0.118965
3  0.817535  0.316914  0.769587  0.027833  0.454849
4  0.410387  0.776413  0.824525  0.986164  0.911503

In [182]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

4.5 ms ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [183]:
%timeit pd.eval("df['A'] + df['B'] / df['C'] - df['D'] * df['E']")

20.5 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [184]:
%timeit df.eval('A + B / C - D * E')

6.4 ms ± 15.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [185]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.781122  0.162240  0.510469  0.432363  0.010421  1.094441
1  0.837288  0.360168  0.408874  0.055812  0.712574  1.678395
2  0.342259  0.156306  0.204718  0.372911  0.118965  1.061416
3  0.817535  0.316914  0.769587  0.027833  0.454849  1.216672
4  0.410387  0.776413  0.824525  0.986164  0.911503  0.453144

In [186]:
df.eval('R = A - B / C + D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.781122  0.162240  0.510469  0.432363  0.010421  0.467803
1  0.837288  0.360168  0.408874  0.055812  0.712574 -0.003819
2  0.342259  0.156306  0.204718  0.372911  0.118965 -0.376898
3  0.817535  0.316914  0.769587  0.027833  0.454849  0.418397
4  0.410387  0.776413  0.824525  0.986164  0.911503  0.367630

In [187]:
col_mean = df.mean(1)
df['A'] + col_mean

0         1.175192
1         1.232438
2         0.478636
3         1.285054
4         1.123157
            ...   
999995    0.795278
999996    0.932788
999997    1.265534
999998   -1.780940
999999    1.045471
Length: 1000000, dtype: float64

In [188]:
df.eval('A + @col_mean')  #@: 외부 변수 참조

0         1.175192
1         1.232438
2         0.478636
3         1.285054
4         1.123157
            ...   
999995    0.795278
999996    0.932788
999997    1.265534
999998   -1.780940
999999    1.045471
Length: 1000000, dtype: float64

In [189]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C < 0.5)]

A         B         C         D         E          R
2       0.342259  0.156306  0.204718  0.372911  0.118965  -0.376898
11      0.355492  0.353428  0.019984  0.770118  0.599985 -16.868220
27      0.435295  0.476361  0.106365  0.644919  0.078758  -3.992449
46      0.076979  0.041044  0.315418  0.028001  0.652714  -0.034869
48      0.393088  0.151261  0.496630  0.213122  0.079488   0.105455
...          ...       ...       ...       ...       ...        ...
999946  0.396718  0.449933  0.432858  0.513077  0.622778  -0.323195
999962  0.346836  0.086640  0.461947  0.420929  0.106181   0.203977
999965  0.486788  0.250917  0.459198  0.714127  0.758958   0.482357
999973  0.327077  0.016679  0.256622  0.373452  0.656836   0.507381
999989  0.249295  0.162785  0.494624  0.574978  0.380736   0.139101

[125077 rows x 6 columns]

In [190]:
pd.eval("df[(df.A < 0.5) & (df.B < 0.5) & (df.C < 0.5)]")

A         B         C         D         E          R
2       0.342259  0.156306  0.204718  0.372911  0.118965  -0.376898
11      0.355492  0.353428  0.019984  0.770118  0.599985 -16.868220
27      0.435295  0.476361  0.106365  0.644919  0.078758  -3.992449
46      0.076979  0.041044  0.315418  0.028001  0.652714  -0.034869
48      0.393088  0.151261  0.496630  0.213122  0.079488   0.105455
...          ...       ...       ...       ...       ...        ...
999946  0.396718  0.449933  0.432858  0.513077  0.622778  -0.323195
999962  0.346836  0.086640  0.461947  0.420929  0.106181   0.203977
999965  0.486788  0.250917  0.459198  0.714127  0.758958   0.482357
999973  0.327077  0.016679  0.256622  0.373452  0.656836   0.507381
999989  0.249295  0.162785  0.494624  0.574978  0.380736   0.139101

[125077 rows x 6 columns]

In [191]:
df.query("(A < 0.5) and (B < 0.5) and (C < 0.5)")

A         B         C         D         E          R
2       0.342259  0.156306  0.204718  0.372911  0.118965  -0.376898
11      0.355492  0.353428  0.019984  0.770118  0.599985 -16.868220
27      0.435295  0.476361  0.106365  0.644919  0.078758  -3.992449
46      0.076979  0.041044  0.315418  0.028001  0.652714  -0.034869
48      0.393088  0.151261  0.496630  0.213122  0.079488   0.105455
...          ...       ...       ...       ...       ...        ...
999946  0.396718  0.449933  0.432858  0.513077  0.622778  -0.323195
999962  0.346836  0.086640  0.461947  0.420929  0.106181   0.203977
999965  0.486788  0.250917  0.459198  0.714127  0.758958   0.482357
999973  0.327077  0.016679  0.256622  0.373452  0.656836   0.507381
999989  0.249295  0.162785  0.494624  0.574978  0.380736   0.139101

[125077 rows x 6 columns]

In [192]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B <col_mean)]

A         B         C         D         E          R
2       0.342259  0.156306  0.204718  0.372911  0.118965  -0.376898
5       0.431720  0.133267  0.941937  0.827362  0.081896   0.357995
11      0.355492  0.353428  0.019984  0.770118  0.599985 -16.868220
16      0.036388  0.015206  0.830293  0.564287  0.217552   0.140837
21      0.191828  0.351972  0.886232  0.777399  0.260446  -0.002856
...          ...       ...       ...       ...       ...        ...
999973  0.327077  0.016679  0.256622  0.373452  0.656836   0.507381
999974  0.475778  0.163764  0.531340  0.485282  0.263012   0.295202
999988  0.486639  0.301727  0.747446  0.226802  0.699618   0.241637
999989  0.249295  0.162785  0.494624  0.574978  0.380736   0.139101
999991  0.379767  0.162738  0.762643  0.582007  0.147479   0.252215

[250022 rows x 6 columns]

In [193]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E          R
2       0.342259  0.156306  0.204718  0.372911  0.118965  -0.376898
5       0.431720  0.133267  0.941937  0.827362  0.081896   0.357995
11      0.355492  0.353428  0.019984  0.770118  0.599985 -16.868220
16      0.036388  0.015206  0.830293  0.564287  0.217552   0.140837
21      0.191828  0.351972  0.886232  0.777399  0.260446  -0.002856
...          ...       ...       ...       ...       ...        ...
999973  0.327077  0.016679  0.256622  0.373452  0.656836   0.507381
999974  0.475778  0.163764  0.531340  0.485282  0.263012   0.295202
999988  0.486639  0.301727  0.747446  0.226802  0.699618   0.241637
999989  0.249295  0.162785  0.494624  0.574978  0.380736   0.139101
999991  0.379767  0.162738  0.762643  0.582007  0.147479   0.252215

[250022 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [194]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [195]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    print(data)
    return pd.DataFrame(data, idx)


In [196]:
df1 = create_df('AB', [1, 2])
df1

{'A': ['a1', 'a2'], 'B': ['b1', 'b2']}


A   B
1  a1  b1
2  a2  b2

In [197]:
df2 = create_df('AB', [3, 4])
df2

{'A': ['a3', 'a4'], 'B': ['b3', 'b4']}


A   B
3  a3  b3
4  a4  b4

In [198]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [199]:
df3 = create_df('AB', [0, 1])
df3

{'A': ['a0', 'a1'], 'B': ['b0', 'b1']}


A   B
0  a0  b0
1  a1  b1

In [200]:
df4 = create_df('CD', [0, 1])
df4

{'C': ['c0', 'c1'], 'D': ['d0', 'd1']}


C   D
0  c0  d0
1  c1  d1

In [201]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [202]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [203]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [204]:
#pd.concat([df1, df3], verify_integrity=True)

In [205]:
pd.concat([df1, df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [206]:
pd.concat([df1, df3], keys=['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [207]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

{'A': ['a1', 'a2'], 'B': ['b1', 'b2'], 'C': ['c1', 'c2']}
{'B': ['b3', 'b4'], 'C': ['c3', 'c4'], 'D': ['d3', 'd4']}


A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [208]:
pd.concat([df5, df6], join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [209]:
df5.append(df6)

/var/folders/_z/xfqh9c3n405462fvjyfgwj7h0000gn/T/ipykernel_8645/551904218.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5.append(df6)


A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [210]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [211]:
df2 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [212]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [213]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                    '학과장': ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [214]:
pd.merge(df3, df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [215]:
df5 = pd.DataFrame({'학과': ['경영학과', '교육학과', '교육학과', '컴퓨터학과', '컴퓨터학과', '통계학과'],
                    '과목': ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [216]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [217]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [218]:
df6 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적': ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [219]:
pd.merge(df1, df6, left_on='학생', right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [220]:
pd.merge(df1, df6, left_on='학생', right_on='이름').drop('이름', axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [221]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [222]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [223]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [224]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [225]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [226]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [227]:
df7 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정'],
                    '주문음식': ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [228]:
df8 = pd.DataFrame({'이름': ['홍길동', '이순신', '김유진'],
                    '주문음료': ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유진   커피

In [229]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [230]:
pd.merge(df7, df8, how='inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [231]:
pd.merge(df7, df8, how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유진  NaN   커피

In [232]:
pd.merge(df7, df8, how='left')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [233]:
pd.merge(df7, df8, how='right')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유진  NaN   커피

In [234]:
df9 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [235]:
df10 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [236]:
pd.merge(df9, df10, on="이름")

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [237]:
pd.merge(df9, df10, on="이름", suffixes=["_인기", "_성적"])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


In [238]:
df = pd.DataFrame([[1, 1.2, np.nan],
                    [2.4, 5.5, 4.2],
                    [np.nan, np.nan, np.nan],
                    [0.44, -3.1, -4.1]],
                    index=[1, 2, 3, 4],
                    columns=['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [239]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [240]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [241]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [242]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [243]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [244]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [245]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [246]:
print(df)
print(df.sum())
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [247]:
print(df)
print(df.prod())
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [248]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [249]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [250]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [251]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [252]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [253]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [254]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [255]:
df['A'].value_counts()

1.00    1
2.40    1
0.44    1
Name: A, dtype: int64

### GroupBy 연산

In [369]:
df = pd.DataFrame({'c1': ['a', 'a', 'b', 'b', 'c', 'd', 'b'],
                'c2': ['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                'c3': np.random.randint(7),
                'c4': np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   3  0.962190
1  a  B   3  0.110833
2  b  B   3  0.205722
3  b  A   3  0.038942
4  c  D   3  0.743692
5  d  C   3  0.866442
6  b  C   3  0.257117

In [370]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [371]:
df['c3'].groupby(df['c1']).mean()

c1
a    3.0
b    3.0
c    3.0
d    3.0
Name: c3, dtype: float64

In [372]:
df['c4'].groupby(df['c2']).std()

c2
A    0.652835
B    0.067097
C    0.430857
D         NaN
Name: c4, dtype: float64

In [373]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.962190
    B     0.110833
b   A     0.038942
    B     0.205722
    C     0.257117
c   D     0.743692
d   C     0.866442
Name: c4, dtype: float64

In [374]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.962190  0.110833       NaN       NaN
b   0.038942  0.205722  0.257117       NaN
c        NaN       NaN       NaN  0.743692
d        NaN       NaN  0.866442       NaN

In [375]:
df.groupby('c1').mean()

c3        c4
c1               
a   3.0  0.536512
b   3.0  0.167261
c   3.0  0.743692
d   3.0  0.866442

In [376]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2               
a  A   3.0  0.962190
   B   3.0  0.110833
b  A   3.0  0.038942
   B   3.0  0.205722
   C   3.0  0.257117
c  D   3.0  0.743692
d  C   3.0  0.866442

In [377]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [378]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   3  0.962190
1  a  B   3  0.110833
b
  c1 c2  c3        c4
2  b  B   3  0.205722
3  b  A   3  0.038942
6  b  C   3  0.257117
c
  c1 c2  c3        c4
4  c  D   3  0.743692
d
  c1 c2  c3        c4
5  d  C   3  0.866442


In [379]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
    print((c1, c2))
    print(group)

('a', 'A')
  c1 c2  c3       c4
0  a  A   3  0.96219
('a', 'B')
  c1 c2  c3        c4
1  a  B   3  0.110833
('b', 'A')
  c1 c2  c3        c4
3  b  A   3  0.038942
('b', 'B')
  c1 c2  c3        c4
2  b  B   3  0.205722
('b', 'C')
  c1 c2  c3        c4
6  b  C   3  0.257117
('c', 'D')
  c1 c2  c3        c4
4  c  D   3  0.743692
('d', 'C')
  c1 c2  c3        c4
5  d  C   3  0.866442


In [380]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.962190
   B   0.110833
b  A   0.038942
   B   0.205722
   C   0.257117
c  D   0.743692
d  C   0.866442

In [381]:
df.groupby('c1')[['c3']].quantile()

c3
c1     
a   3.0
b   3.0
c   3.0
d   3.0

In [382]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [383]:
df.groupby('c1')['c4'].median()

c1
a    0.536512
b    0.205722
c    0.743692
d    0.866442
Name: c4, dtype: float64

In [384]:
df.groupby('c1')['c4'].std()

c1
a    0.602000
b    0.114059
c         NaN
d         NaN
Name: c4, dtype: float64

In [385]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.962190  0.962190  0.962190
   B   0.110833  0.110833  0.110833
b  A   0.038942  0.038942  0.038942
   B   0.205722  0.205722  0.205722
   C   0.257117  0.257117  0.257117
c  D   0.743692  0.743692  0.743692
d  C   0.866442  0.866442  0.866442

In [386]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean()

c1 c2        c4
0  a  A  0.962190
1  a  B  0.110833
2  b  A  0.038942
3  b  B  0.205722
4  b  C  0.257117
5  c  D  0.743692
6  d  C  0.866442

In [387]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.962190
    B     0.110833
b   A     0.038942
    B     0.205722
    C     0.257117
c   D     0.743692
d   C     0.866442
Name: c4, dtype: float64

In [422]:
def top(df, n=3, column='c1'):
    return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   3  0.205722
3  b  A   3  0.038942
6  b  C   3  0.257117
4  c  D   3  0.743692
5  d  C   3  0.866442

In [421]:
df.groupby('c1').apply(top)
# 위의 top함수에서 column='c1'으로 하면 정렬이 안되는데
# c2로 하면 정렬이 잘 됨. 왜 그런걸까...



c1 c2  c3        c4
c1                      
a  0  a  A   3  0.962190
   1  a  B   3  0.110833
b  3  b  A   3  0.038942
   2  b  B   3  0.205722
   6  b  C   3  0.257117
c  4  c  D   3  0.743692
d  5  d  C   3  0.866442

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly