<a href="https://colab.research.google.com/github/wjlee611/studyPython_Library/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [1]:
import numpy as np
import pandas as pd
pd.__version__

'1.3.4'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1], 
                index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [8]:
s['c']

0.5

In [9]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s

True

In [11]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
                index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [12]:
s[4]

0.25

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts()

0.00    1
0.25    1
0.50    1
0.75    1
1.00    1
dtype: int64

In [16]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시': 9720846,
            '부산광역시': 3404423,
            '인천광역시': 2947217,
            '대구광역시': 2427954,
            '대전광역시': 1471040,
            '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [20]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, {'A':4, 'B':5, 'C':7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5, 5),
            columns=['A', 'B', 'C', 'D', 'E'],
            index=[1, 2, 3, 4, 5])

A         B         C         D         E
1  0.426260  0.243609  0.935575  0.414164  0.479601
2  0.848119  0.876675  0.144824  0.226518  0.606234
3  0.195545  0.097500  0.495736  0.098395  0.769351
4  0.467017  0.464643  0.919516  0.242573  0.225567
5  0.671700  0.988679  0.673663  0.094006  0.390805

In [22]:
male_tuple = {'서울특별시': 4732275,
            '부산광역시': 1668618,
            '인천광역시': 1476813,
            '대구광역시': 1198815,
            '대전광역시': 734441,
            '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시': 4988571,
            '부산광역시': 1735805,
            '인천광역시': 1470404,
            '대구광역시': 1229139,
            '대전광역시': 736599,
            '광주광역시': 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수': population,
                        '남자인구수': male,
                        '여자인구수': female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [26]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [27]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [28]:
korea_df['서울특별시':'인천광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체


In [29]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [30]:
idx[1]

4

In [31]:
idx[0:5:2]

Int64Index([2, 6, 10], dtype='int64')

In [32]:
idx[-1::]

Int64Index([10], dtype='int64')

In [33]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [34]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [35]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])

print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(2))
print(idx1 ^ idx2)

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


/Users/wjlee/opt/anaconda3/envs/study_ML_37/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  
/Users/wjlee/opt/anaconda3/envs/study_ML_37/lib/python3.7/site-packages/ipykernel_launcher.py:10: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  # Remove the CWD from sys.path while we load stuff.
/Users/wjlee/opt/anaconda3/envs/study_ML_37/lib/python3.7/site-packages/ipykernel_launcher.py:13: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  del sys.path[0]




---



## 인덱싱(Indexing)

In [36]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1],
            index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [37]:
s['b']

0.25

In [38]:
'b' in s

True

In [39]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [41]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [42]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[(s > 0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [45]:
s[(['a', 'c', 'e'])]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [46]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
            index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [47]:
s[1]

'a'

In [48]:
s[2:4]

5    c
7    d
dtype: object

In [49]:
s.iloc[1]

'b'

In [50]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [51]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [52]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [53]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [54]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [55]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [57]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [58]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [59]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [60]:
korea_df.T

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [61]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [62]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [63]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [64]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [65]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [66]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [67]:
korea_df.loc[(korea_df.남여비율 > 100)]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남여비율 < 100)]

인구수    남자인구수    여자인구수       남여비율
서울특별시  9720846  4732275  4988571  94.862336
부산광역시  3404423  1668618  1735805  96.129346

In [69]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [70]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [71]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
            ('부산광역시', 2010), ('부산광역시', 2020),
            ('인천광역시', 2010), ('인천광역시', 2020),
            ('대구광역시', 2010), ('대구광역시', 2020),
            ('대전광역시', 2010), ('대전광역시', 2020),
            ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [72]:
pop_tuples = [10312545, 9720846,
            2567910, 3404423,
            2758296, 2947217,
            2511676, 2427954,
            1503664, 1471040,
            1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [73]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [74]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [75]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [76]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [77]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [78]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [79]:
male_tuple = [5111259, 4732275,
            1773170, 1668618,
            1390356, 1476813,
            1255245, 1198815,
            753648, 734441,
            721780, 720060]
male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [80]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [81]:
female_tuple = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732856, 734988]
female_tuple

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [82]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple,
                        '여자인구수': female_tuple})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [83]:
ratio = korea_mdf['남자인구수'] / korea_mdf.여자인구수 * 100
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [84]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [85]:
korea_mdf = pd.DataFrame({'총인구수': population,
                        '남자인구수': male_tuple,
                        '여자인구수': female_tuple,
                        '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [86]:
df = pd.DataFrame(np.random.rand(6, 3),
                index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.168993  0.744694  0.170828
  2  0.497494  0.115184  0.884300
b 1  0.868078  0.628188  0.569823
  2  0.840043  0.167987  0.629102
c 1  0.781733  0.859881  0.993059
  2  0.906461  0.538412  0.496616

In [87]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [88]:
pd.MultiIndex.from_tuples([('a', 1),
                        ('a', 2),
                        ('b', 1),
                        ('b', 2),
                        ('c', 1),
                        ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
pd.MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
            codes=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [92]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [93]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -1.16  1.01 -1.39  0.51 -1.16 -0.19
      2     -0.22 -0.82  0.59  1.92  2.19 -1.02
b     1     -0.43 -0.13 -0.85  0.46 -0.10 -1.80
      2      0.41  0.12 -0.41  0.11 -0.74 -2.53
c     1      0.51  1.53  0.85 -0.79  0.52 -1.71
      2     -0.64 -1.22 -2.50  0.24 -0.21 -0.80

In [94]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -1.39  0.51
      2      0.59  1.92
b     1     -0.85  0.46
      2     -0.41  0.11
c     1      0.85 -0.79
      2     -2.50  0.24

#### 인덱싱 및 슬라이싱

In [95]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [96]:
population['인천광역시', 2010]

2758296

In [97]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [98]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [99]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [100]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -1.16  1.01 -1.39  0.51 -1.16 -0.19
      2     -0.22 -0.82  0.59  1.92  2.19 -1.02
b     1     -0.43 -0.13 -0.85  0.46 -0.10 -1.80
      2      0.41  0.12 -0.41  0.11 -0.74 -2.53
c     1      0.51  1.53  0.85 -0.79  0.52 -1.71
      2     -0.64 -1.22 -2.50  0.24 -0.21 -0.80

In [101]:
mdf['c2', 1]

name1  name2
a      1       -1.39
       2        0.59
b      1       -0.85
       2       -0.41
c      1        0.85
       2       -2.50
Name: (c2, 1), dtype: float64

In [102]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -1.16  1.01 -1.39  0.51
      2     -0.22 -0.82  0.59  1.92
b     1     -0.43 -0.13 -0.85  0.46

In [103]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -1.39
       2        0.59
b      1       -0.85
       2       -0.41
c      1        0.85
       2       -2.50
Name: (c2, 1), dtype: float64

In [104]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.82  1.92 -1.02
b     2      0.12  0.11 -2.53
c     2     -1.22  0.24 -0.80

#### 다중 인덱스 재정렬

In [105]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [106]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [107]:
#korea_mdf['서울특별시':'인천광역시']

korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [108]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [109]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남여비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [110]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남여비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [111]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [112]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [113]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [114]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [115]:
idx_flat.set_index('행정구역', '년도')

/Users/wjlee/opt/anaconda3/envs/study_ML_37/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.set_index except for the argument 'keys' will be keyword-only
  """Entry point for launching an IPython kernel.


년도      총인구수    남자인구수    여자인구수        남여비율
행정구역                                               
광주광역시  2010   1454636   721780   732856   98.488653
광주광역시  2020   1455048   720060   734988   97.968946
대구광역시  2010   2511676  1255245  1256431   99.905606
대구광역시  2020   2427954  1198815  1229139   97.532907
대전광역시  2010   1503664   753648   750016  100.484256
대전광역시  2020   1471040   734441   736599   99.707032
부산광역시  2010   2567910  1773170  1794740   98.798155
부산광역시  2020   3404423  1668618  1735805   96.129346
서울특별시  2010  10312545  5111259  5201286   98.269140
서울특별시  2020   9720846  4732275  4988571   94.862336
인천광역시  2010   2758296  1390356  1367940  101.638668
인천광역시  2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [116]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    7
1    1
2    5
3    1
4    5
dtype: int64

In [117]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                columns=['A', 'B', 'C'])
df

A  B  C
0  1  5  3
1  0  6  8
2  3  0  9

In [118]:
np.exp(s)

0    1096.633158
1       2.718282
2     148.413159
3       2.718282
4     148.413159
dtype: float64

In [119]:
np.cos(df * np.pi / 4)

A             B         C
0  0.707107 -7.071068e-01 -0.707107
1  1.000000 -1.836970e-16  1.000000
2 -0.707107  1.000000e+00  0.707107

In [120]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [121]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [122]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                columns=list('ACD'))
df1

A   C  D
0   9  11  4
1  18   0  1
2   0  15  9

In [123]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                columns=list('BAECD'))
df2

B   A   E   C   D
0  14   6  10  15   5
1   9   2  12  13  16
2  17  14  16   6  17
3   3  12   3  13   0
4  18  18   3   4  19

In [124]:
df1 + df2

A   B     C     D   E
0  15.0 NaN  26.0   9.0 NaN
1  20.0 NaN  13.0  17.0 NaN
2  14.0 NaN  21.0  26.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [125]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  15.000000  21.444444  26.000000   9.000000  17.444444
1  20.000000  16.444444  13.000000  17.000000  19.444444
2  14.000000  24.444444  21.000000  26.000000  23.444444
3  19.444444  10.444444  20.444444   7.444444  10.444444
4  25.444444  25.444444  11.444444  26.444444  10.444444

### 연산자 범용 함수


#### add()

In [126]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[6, 9, 4],
       [6, 5, 7],
       [1, 5, 9]])

In [127]:
a + a[0]

array([[12, 18,  8],
       [12, 14, 11],
       [ 7, 14, 13]])

In [128]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  6  9  4
1  6  5  7
2  1  5  9

In [129]:
df + df.iloc[0]

A   B   C
0  12  18   8
1  12  14  11
2   7  14  13

In [130]:
df.add(df.iloc[0])

A   B   C
0  12  18   8
1  12  14  11
2   7  14  13

#### sub() / subtract()

In [131]:
a

array([[6, 9, 4],
       [6, 5, 7],
       [1, 5, 9]])

In [132]:
a - a[0]

array([[ 0,  0,  0],
       [ 0, -4,  3],
       [-5, -4,  5]])

In [133]:
df

A  B  C
0  6  9  4
1  6  5  7
2  1  5  9

In [134]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  0 -4  3
2 -5 -4  5

In [135]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  0 -4  3
2 -5 -4  5

In [136]:
df.subtract(df['B'], axis=0)

A  B  C
0 -3  0 -5
1  1  0  2
2 -4  0  4

#### mul() / multply()




In [137]:
a

array([[6, 9, 4],
       [6, 5, 7],
       [1, 5, 9]])

In [138]:
a * a[1]

array([[36, 45, 28],
       [36, 25, 49],
       [ 6, 25, 63]])

In [139]:
df

A  B  C
0  6  9  4
1  6  5  7
2  1  5  9

In [140]:
df * df.iloc[1]

A   B   C
0  36  45  28
1  36  25  49
2   6  25  63

In [141]:
df.mul(df.iloc[1])

A   B   C
0  36  45  28
1  36  25  49
2   6  25  63

In [142]:
df.multiply(df.iloc[2])

A   B   C
0  6  45  36
1  6  25  63
2  1  25  81

#### truediv() /  div() / divide() / floordiv()

In [143]:
a

array([[6, 9, 4],
       [6, 5, 7],
       [1, 5, 9]])

In [144]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.        , 0.55555556, 1.75      ],
       [0.16666667, 0.55555556, 2.25      ]])

In [145]:
df

A  B  C
0  6  9  4
1  6  5  7
2  1  5  9

In [146]:
df / df.iloc[0]

A         B     C
0  1.000000  1.000000  1.00
1  1.000000  0.555556  1.75
2  0.166667  0.555556  2.25

In [147]:
df.truediv(df.iloc[0])

A         B     C
0  1.000000  1.000000  1.00
1  1.000000  0.555556  1.75
2  0.166667  0.555556  2.25

In [148]:
df.div(df.iloc[1])

A    B         C
0  1.000000  1.8  0.571429
1  1.000000  1.0  1.000000
2  0.166667  1.0  1.285714

In [149]:
df.divide(df.iloc[2])

A    B         C
0  6.0  1.8  0.444444
1  6.0  1.0  0.777778
2  1.0  1.0  1.000000

In [150]:
a // a[0]

array([[1, 1, 1],
       [1, 0, 1],
       [0, 0, 2]])

In [151]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  0  1
2  0  0  2

#### mod()

In [152]:
a

array([[6, 9, 4],
       [6, 5, 7],
       [1, 5, 9]])

In [153]:
a % a[0]

array([[0, 0, 0],
       [0, 5, 3],
       [1, 5, 1]])

In [154]:
df

A  B  C
0  6  9  4
1  6  5  7
2  1  5  9

In [155]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  0  5  3
2  1  5  1

#### pow()

In [156]:
a

array([[6, 9, 4],
       [6, 5, 7],
       [1, 5, 9]])

In [157]:
a ** a[0]

array([[    46656, 387420489,       256],
       [    46656,   1953125,      2401],
       [        1,   1953125,      6561]])

In [158]:
df

A  B  C
0  6  9  4
1  6  5  7
2  1  5  9

In [159]:
df.pow(df.iloc[0])

A          B     C
0  46656  387420489   256
1  46656    1953125  2401
2      1    1953125  6561

In [160]:
row = df.iloc[0, ::2]
row

A    6
C    4
Name: 0, dtype: int64

In [161]:
df - row

A   B    C
0  0.0 NaN  0.0
1  0.0 NaN  3.0
2 -5.0 NaN  5.0

### 정렬(Sort)

In [162]:
s = pd.Series(range(5), index=list('ADBCE'))
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [163]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [164]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [165]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                                    index=[2, 4, 1, 3],
                                    columns=list('BDAC'))
df

B  D  A  C
2  5  9  3  0
4  4  7  9  5
1  8  3  4  7
3  9  3  4  2

In [166]:
df.sort_index()

B  D  A  C
1  8  3  4  7
2  5  9  3  0
3  9  3  4  2
4  4  7  9  5

In [167]:
df.sort_index(axis=1)

A  B  C  D
2  3  5  0  9
4  9  4  5  7
1  4  8  7  3
3  4  9  2  3

In [168]:
df.sort_values(by='A')

B  D  A  C
2  5  9  3  0
1  8  3  4  7
3  9  3  4  2
4  4  7  9  5

In [169]:
df.sort_values(by=['A', 'C'])

B  D  A  C
2  5  9  3  0
3  9  3  4  2
1  8  3  4  7
4  4  7  9  5

### 순위(Ranking)


In [170]:
s = pd.Series([-2, 4, 5, 7, 2, -1, 4, 9, 4, -1])
s

0   -2
1    4
2    5
3    7
4    2
5   -1
6    4
7    9
8    4
9   -1
dtype: int64

In [171]:
s.rank()

0     1.0
1     6.0
2     8.0
3     9.0
4     4.0
5     2.5
6     6.0
7    10.0
8     6.0
9     2.5
dtype: float64

In [172]:
s.rank(method='first')

0     1.0
1     5.0
2     8.0
3     9.0
4     4.0
5     2.0
6     6.0
7    10.0
8     7.0
9     3.0
dtype: float64

In [173]:
s.rank(method='min')

0     1.0
1     5.0
2     8.0
3     9.0
4     4.0
5     2.0
6     5.0
7    10.0
8     5.0
9     2.0
dtype: float64

### 고성능 연산

In [174]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [175]:
%timeit df1 + df2 + df3 + df4

7.95 ms ± 85.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [176]:
%timeit pd.eval('df1 + df2 + df3 + df4')

5.1 ms ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [177]:
%timeit df1 * -df2 / (-df3 * df4)

14.5 ms ± 223 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [178]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

5.51 ms ± 257 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [179]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

9.55 ms ± 318 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [180]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

11.2 ms ± 188 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [181]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=list('ABCDE'))
df.head()

A         B         C         D         E
0  0.045774  0.975336  0.649040  0.927788  0.825934
1  0.324503  0.762620  0.470373  0.566045  0.954133
2  0.706391  0.543369  0.784455  0.994484  0.852799
3  0.733963  0.232357  0.372880  0.778815  0.214627
4  0.789938  0.456190  0.703442  0.794796  0.614962

In [182]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

3.74 ms ± 71.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [183]:
#%timeit pd.eval("df['A'] + df['B'] / df['C'] - df['D'] * df['E']")
#python 3.9.9에선 작동함
%timeit pd.eval("df.A + df.B / df.C - df.D * df.E")

1.81 ms ± 24.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [184]:
%timeit df.eval('A + B / C - D * E')

2.74 ms ± 66.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [185]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.045774  0.975336  0.649040  0.927788  0.825934  0.782218
1  0.324503  0.762620  0.470373  0.566045  0.954133  1.405731
2  0.706391  0.543369  0.784455  0.994484  0.852799  0.550968
3  0.733963  0.232357  0.372880  0.778815  0.214627  1.189951
4  0.789938  0.456190  0.703442  0.794796  0.614962  0.949679

In [186]:
df.eval('R = A - B / C + D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.045774  0.975336  0.649040  0.927788  0.825934 -0.690670
1  0.324503  0.762620  0.470373  0.566045  0.954133 -0.756724
2  0.706391  0.543369  0.784455  0.994484  0.852799  0.861815
3  0.733963  0.232357  0.372880  0.778815  0.214627  0.277976
4  0.789938  0.456190  0.703442  0.794796  0.614962  0.630196

In [187]:
col_mean = df.mean(1)
df['A'] + col_mean

0         0.501308
1         0.711328
2         1.496943
3         1.169066
4         1.454858
            ...   
999995    0.124556
999996    0.403737
999997    1.295091
999998    0.382681
999999    1.048113
Length: 1000000, dtype: float64

In [188]:
df.eval('A + @col_mean')  #@: 외부 변수 참조

0         0.501308
1         0.711328
2         1.496943
3         1.169066
4         1.454858
            ...   
999995    0.124556
999996    0.403737
999997    1.295091
999998    0.382681
999999    1.048113
Length: 1000000, dtype: float64

In [189]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C < 0.5)]

A         B         C         D         E          R
6       0.178748  0.409609  0.422959  0.609745  0.004123  -0.787175
12      0.487340  0.233595  0.356902  0.185667  0.148487  -0.139598
22      0.324898  0.144079  0.209422  0.207813  0.063572  -0.349873
31      0.156400  0.359984  0.427178  0.820849  0.920796   0.069532
43      0.037114  0.181367  0.155790  0.061775  0.404809  -1.102057
...          ...       ...       ...       ...       ...        ...
999962  0.281802  0.465144  0.326395  0.516592  0.749495  -0.756111
999975  0.269639  0.259686  0.019533  0.804973  0.815002 -12.369198
999977  0.243848  0.174044  0.455387  0.337917  0.081376  -0.110843
999995  0.034205  0.147858  0.072874  0.853840  0.770340  -1.337013
999996  0.352490  0.443432  0.281203  0.217133  0.195248  -1.182026

[124959 rows x 6 columns]

In [190]:
pd.eval("df[(df.A < 0.5) & (df.B < 0.5) & (df.C < 0.5)]")

A         B         C         D         E          R
6       0.178748  0.409609  0.422959  0.609745  0.004123  -0.787175
12      0.487340  0.233595  0.356902  0.185667  0.148487  -0.139598
22      0.324898  0.144079  0.209422  0.207813  0.063572  -0.349873
31      0.156400  0.359984  0.427178  0.820849  0.920796   0.069532
43      0.037114  0.181367  0.155790  0.061775  0.404809  -1.102057
...          ...       ...       ...       ...       ...        ...
999962  0.281802  0.465144  0.326395  0.516592  0.749495  -0.756111
999975  0.269639  0.259686  0.019533  0.804973  0.815002 -12.369198
999977  0.243848  0.174044  0.455387  0.337917  0.081376  -0.110843
999995  0.034205  0.147858  0.072874  0.853840  0.770340  -1.337013
999996  0.352490  0.443432  0.281203  0.217133  0.195248  -1.182026

[124959 rows x 6 columns]

In [191]:
df.query("(A < 0.5) and (B < 0.5) and (C < 0.5)")

A         B         C         D         E          R
6       0.178748  0.409609  0.422959  0.609745  0.004123  -0.787175
12      0.487340  0.233595  0.356902  0.185667  0.148487  -0.139598
22      0.324898  0.144079  0.209422  0.207813  0.063572  -0.349873
31      0.156400  0.359984  0.427178  0.820849  0.920796   0.069532
43      0.037114  0.181367  0.155790  0.061775  0.404809  -1.102057
...          ...       ...       ...       ...       ...        ...
999962  0.281802  0.465144  0.326395  0.516592  0.749495  -0.756111
999975  0.269639  0.259686  0.019533  0.804973  0.815002 -12.369198
999977  0.243848  0.174044  0.455387  0.337917  0.081376  -0.110843
999995  0.034205  0.147858  0.072874  0.853840  0.770340  -1.337013
999996  0.352490  0.443432  0.281203  0.217133  0.195248  -1.182026

[124959 rows x 6 columns]

In [192]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B <col_mean)]

A         B         C         D         E         R
6       0.178748  0.409609  0.422959  0.609745  0.004123 -0.787175
12      0.487340  0.233595  0.356902  0.185667  0.148487 -0.139598
13      0.109669  0.099254  0.977260  0.887020  0.333869  0.304254
19      0.098582  0.092973  0.596501  0.545067  0.991664  0.483241
22      0.324898  0.144079  0.209422  0.207813  0.063572 -0.349873
...          ...       ...       ...       ...       ...       ...
999977  0.243848  0.174044  0.455387  0.337917  0.081376 -0.110843
999979  0.294530  0.439862  0.716062  0.913893  0.363409  0.012367
999987  0.373946  0.215852  0.929614  0.705169  0.864052  0.751053
999995  0.034205  0.147858  0.072874  0.853840  0.770340 -1.337013
999996  0.352490  0.443432  0.281203  0.217133  0.195248 -1.182026

[249319 rows x 6 columns]

In [193]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
6       0.178748  0.409609  0.422959  0.609745  0.004123 -0.787175
12      0.487340  0.233595  0.356902  0.185667  0.148487 -0.139598
13      0.109669  0.099254  0.977260  0.887020  0.333869  0.304254
19      0.098582  0.092973  0.596501  0.545067  0.991664  0.483241
22      0.324898  0.144079  0.209422  0.207813  0.063572 -0.349873
...          ...       ...       ...       ...       ...       ...
999977  0.243848  0.174044  0.455387  0.337917  0.081376 -0.110843
999979  0.294530  0.439862  0.716062  0.913893  0.363409  0.012367
999987  0.373946  0.215852  0.929614  0.705169  0.864052  0.751053
999995  0.034205  0.147858  0.072874  0.853840  0.770340 -1.337013
999996  0.352490  0.443432  0.281203  0.217133  0.195248 -1.182026

[249319 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [194]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [195]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    print(data)
    return pd.DataFrame(data, idx)


In [196]:
df1 = create_df('AB', [1, 2])
df1

{'A': ['a1', 'a2'], 'B': ['b1', 'b2']}


A   B
1  a1  b1
2  a2  b2

In [197]:
df2 = create_df('AB', [3, 4])
df2

{'A': ['a3', 'a4'], 'B': ['b3', 'b4']}


A   B
3  a3  b3
4  a4  b4

In [198]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [199]:
df3 = create_df('AB', [0, 1])
df3

{'A': ['a0', 'a1'], 'B': ['b0', 'b1']}


A   B
0  a0  b0
1  a1  b1

In [200]:
df4 = create_df('CD', [0, 1])
df4

{'C': ['c0', 'c1'], 'D': ['d0', 'd1']}


C   D
0  c0  d0
1  c1  d1

In [201]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [202]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [203]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [204]:
#pd.concat([df1, df3], verify_integrity=True)

In [205]:
pd.concat([df1, df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [206]:
pd.concat([df1, df3], keys=['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [207]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

{'A': ['a1', 'a2'], 'B': ['b1', 'b2'], 'C': ['c1', 'c2']}
{'B': ['b3', 'b4'], 'C': ['c3', 'c4'], 'D': ['d3', 'd4']}


A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [208]:
pd.concat([df5, df6], join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [209]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [210]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [211]:
df2 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [212]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [213]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                    '학과장': ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [214]:
pd.merge(df3, df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [215]:
df5 = pd.DataFrame({'학과': ['경영학과', '교육학과', '교육학과', '컴퓨터학과', '컴퓨터학과', '통계학과'],
                    '과목': ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [216]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [217]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [218]:
df6 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적': ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [219]:
pd.merge(df1, df6, left_on='학생', right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [220]:
pd.merge(df1, df6, left_on='학생', right_on='이름').drop('이름', axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [221]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [222]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [223]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [224]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [225]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [226]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [227]:
df7 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정'],
                    '주문음식': ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [228]:
df8 = pd.DataFrame({'이름': ['홍길동', '이순신', '김유진'],
                    '주문음료': ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유진   커피

In [229]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [230]:
pd.merge(df7, df8, how='inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [231]:
pd.merge(df7, df8, how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유진  NaN   커피

In [232]:
pd.merge(df7, df8, how='left')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [233]:
pd.merge(df7, df8, how='right')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유진  NaN   커피

In [234]:
df9 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [235]:
df10 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [236]:
pd.merge(df9, df10, on="이름")

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [237]:
pd.merge(df9, df10, on="이름", suffixes=["_인기", "_성적"])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


In [238]:
df = pd.DataFrame([[1, 1.2, np.nan],
                    [2.4, 5.5, 4.2],
                    [np.nan, np.nan, np.nan],
                    [0.44, -3.1, -4.1]],
                    index=[1, 2, 3, 4],
                    columns=['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [239]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [240]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [241]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [242]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [243]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [244]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [245]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [246]:
print(df)
print(df.sum())
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [247]:
print(df)
print(df.prod())
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [248]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [249]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [250]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [251]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [252]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [253]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [254]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [255]:
df['A'].value_counts()

1.00    1
2.40    1
0.44    1
Name: A, dtype: int64

### GroupBy 연산

In [256]:
df = pd.DataFrame({'c1': ['a', 'a', 'b', 'b', 'c', 'd', 'b'],
                'c2': ['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                'c3': np.random.randint(7),
                'c4': np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   4  0.262206
1  a  B   4  0.609604
2  b  B   4  0.610999
3  b  A   4  0.423829
4  c  D   4  0.898797
5  d  C   4  0.204751
6  b  C   4  0.200867

In [257]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [258]:
df['c3'].groupby(df['c1']).mean()

c1
a    4.0
b    4.0
c    4.0
d    4.0
Name: c3, dtype: float64

In [259]:
df['c4'].groupby(df['c2']).std()

c2
A    0.114285
B    0.000987
C    0.002746
D         NaN
Name: c4, dtype: float64

In [260]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.262206
    B     0.609604
b   A     0.423829
    B     0.610999
    C     0.200867
c   D     0.898797
d   C     0.204751
Name: c4, dtype: float64

In [261]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.262206  0.609604       NaN       NaN
b   0.423829  0.610999  0.200867       NaN
c        NaN       NaN       NaN  0.898797
d        NaN       NaN  0.204751       NaN

In [262]:
df.groupby('c1').mean()

c3        c4
c1               
a   4.0  0.435905
b   4.0  0.411898
c   4.0  0.898797
d   4.0  0.204751

In [263]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2               
a  A   4.0  0.262206
   B   4.0  0.609604
b  A   4.0  0.423829
   B   4.0  0.610999
   C   4.0  0.200867
c  D   4.0  0.898797
d  C   4.0  0.204751

In [264]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [265]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   4  0.262206
1  a  B   4  0.609604
b
  c1 c2  c3        c4
2  b  B   4  0.610999
3  b  A   4  0.423829
6  b  C   4  0.200867
c
  c1 c2  c3        c4
4  c  D   4  0.898797
d
  c1 c2  c3        c4
5  d  C   4  0.204751


In [266]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
    print((c1, c2))
    print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   4  0.262206
('a', 'B')
  c1 c2  c3        c4
1  a  B   4  0.609604
('b', 'A')
  c1 c2  c3        c4
3  b  A   4  0.423829
('b', 'B')
  c1 c2  c3        c4
2  b  B   4  0.610999
('b', 'C')
  c1 c2  c3        c4
6  b  C   4  0.200867
('c', 'D')
  c1 c2  c3        c4
4  c  D   4  0.898797
('d', 'C')
  c1 c2  c3        c4
5  d  C   4  0.204751


In [267]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.262206
   B   0.609604
b  A   0.423829
   B   0.610999
   C   0.200867
c  D   0.898797
d  C   0.204751

In [268]:
df.groupby('c1')[['c3']].quantile()

c3
c1     
a   4.0
b   4.0
c   4.0
d   4.0

In [269]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [270]:
df.groupby('c1')['c4'].median()

c1
a    0.435905
b    0.423829
c    0.898797
d    0.204751
Name: c4, dtype: float64

In [271]:
df.groupby('c1')['c4'].std()

c1
a    0.245647
b    0.205326
c         NaN
d         NaN
Name: c4, dtype: float64

In [272]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.262206  0.262206  0.262206
   B   0.609604  0.609604  0.609604
b  A   0.423829  0.423829  0.423829
   B   0.610999  0.610999  0.610999
   C   0.200867  0.200867  0.200867
c  D   0.898797  0.898797  0.898797
d  C   0.204751  0.204751  0.204751

In [273]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean()

c1 c2        c4
0  a  A  0.262206
1  a  B  0.609604
2  b  A  0.423829
3  b  B  0.610999
4  b  C  0.200867
5  c  D  0.898797
6  d  C  0.204751

In [274]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.262206
    B     0.609604
b   A     0.423829
    B     0.610999
    C     0.200867
c   D     0.898797
d   C     0.204751
Name: c4, dtype: float64

In [275]:
def top(df, n=3, column='c1'):
    return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   4  0.610999
3  b  A   4  0.423829
6  b  C   4  0.200867
4  c  D   4  0.898797
5  d  C   4  0.204751

In [276]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   4  0.262206
   1  a  B   4  0.609604
b  2  b  B   4  0.610999
   3  b  A   4  0.423829
   6  b  C   4  0.200867
c  4  c  D   4  0.898797
d  5  d  C   4  0.204751

### 피벗 테이블(Pivot Table)


In [277]:
df.pivot_table(['c3', 'c4'],
                index=['c1'],
                columns=['c2'])

c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   4.0  4.0  NaN  NaN  0.262206  0.609604       NaN       NaN
b   4.0  4.0  4.0  NaN  0.423829  0.610999  0.200867       NaN
c   NaN  NaN  NaN  4.0       NaN       NaN       NaN  0.898797
d   NaN  NaN  4.0  NaN       NaN       NaN  0.204751       NaN

In [278]:
df.pivot_table(['c3', 'c4'],
                index=['c1'],
                columns=['c2'],
                margins=True)

c3                            c4                                        
c2     A    B    C    D  All         A         B         C         D       All
c1                                                                            
a    4.0  4.0  NaN  NaN  4.0  0.262206  0.609604       NaN       NaN  0.435905
b    4.0  4.0  4.0  NaN  4.0  0.423829  0.610999  0.200867       NaN  0.411898
c    NaN  NaN  NaN  4.0  4.0       NaN       NaN       NaN  0.898797  0.898797
d    NaN  NaN  4.0  NaN  4.0       NaN       NaN  0.204751       NaN  0.204751
All  4.0  4.0  4.0  4.0  4.0  0.343017  0.610301  0.202809  0.898797  0.458722

In [279]:
df.pivot_table(['c3', 'c4'],
                index=['c1'],
                columns=['c2'],
                margins=True,
                aggfunc=sum)

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    4.0  4.0  NaN  NaN   8  0.262206  0.609604       NaN       NaN  0.871809
b    4.0  4.0  4.0  NaN  12  0.423829  0.610999  0.200867       NaN  1.235695
c    NaN  NaN  NaN  4.0   4       NaN       NaN       NaN  0.898797  0.898797
d    NaN  NaN  4.0  NaN   4       NaN       NaN  0.204751       NaN  0.204751
All  8.0  8.0  8.0  4.0  28  0.686035  1.220603  0.405618  0.898797  3.211053

In [280]:
df.pivot_table(['c3', 'c4'],
                index=['c1'],
                columns=['c2'],
                margins=True,
                aggfunc=sum,
                fill_value=0)

c3                     c4                                        
c2   A  B  C  D All         A         B         C         D       All
c1                                                                   
a    4  4  0  0   8  0.262206  0.609604  0.000000  0.000000  0.871809
b    4  4  4  0  12  0.423829  0.610999  0.200867  0.000000  1.235695
c    0  0  0  4   4  0.000000  0.000000  0.000000  0.898797  0.898797
d    0  0  4  0   4  0.000000  0.000000  0.204751  0.000000  0.204751
All  8  8  8  4  28  0.686035  1.220603  0.405618  0.898797  3.211053

In [281]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [282]:
pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)

c2     A    B    C    D  All
c1                          
a    4.0  4.0  NaN  NaN    8
b    4.0  4.0  4.0  NaN   12
c    NaN  NaN  NaN  4.0    4
d    NaN  NaN  4.0  NaN    4
All  8.0  8.0  8.0  4.0   28

### 범주형(Categorical) 데이터


In [283]:
s = pd.Series(['c1', 'c2', 'c1', 'c2', 'c1'] * 2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [284]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [285]:
pd.value_counts(s)

c1    6
c2    4
dtype: int64

In [286]:
code = pd.Series([0, 1, 0, 1, 0] * 2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [287]:
d = pd.Series(['c1', 'c2'])
d

0    c1
1    c2
dtype: object

In [288]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [289]:
df = pd.DataFrame({'id': np.arange(len(s)),
                    'c': s,
                    'v': np.random.randint(1000, 5000, size=len(s))})
df

id   c     v
0   0  c1  3232
1   1  c2  1416
2   2  c1  2816
3   3  c2  2783
4   4  c1  4304
5   5  c1  2191
6   6  c2  4946
7   7  c1  3328
8   8  c2  2666
9   9  c1  3914

In [290]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [291]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [292]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [293]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [294]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [295]:
c = pd.Categorical(['c1', 'c2', 'c3', 'c1', 'c2'])
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [296]:
categories = ['c1', 'c2', 'c3']
codes = [0, 1, 2, 0, 1]
c = pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [297]:
pd.Categorical.from_codes(codes, categories, ordered=True)

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [298]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [299]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [300]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [301]:
c = c.set_categories(['c1', 'c2', 'c3', 'c4', 'c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [302]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [303]:
c[c.isin(['c1', 'c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [304]:
c = c.remove_unused_categories()

In [305]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

## 문자열 연산

#### 문자열 연산자

In [306]:
name_tuple = ['Woong', 'Lee', 'Steven Jobs', 'Larry Page', 'Elon Musk', None, 'Bill Gates', 'Mark', 'Jeff']
names = pd.Series(name_tuple)
names

0          Woong
1            Lee
2    Steven Jobs
3     Larry Page
4      Elon Musk
5           None
6     Bill Gates
7           Mark
8           Jeff
dtype: object

In [307]:
names.str.lower()

0          woong
1            lee
2    steven jobs
3     larry page
4      elon musk
5           None
6     bill gates
7           mark
8           jeff
dtype: object

In [308]:
names.str.len()

0     5.0
1     3.0
2    11.0
3    10.0
4     9.0
5     NaN
6    10.0
7     4.0
8     4.0
dtype: float64

In [309]:
names.str.split()

0           [Woong]
1             [Lee]
2    [Steven, Jobs]
3     [Larry, Page]
4      [Elon, Musk]
5              None
6     [Bill, Gates]
7            [Mark]
8            [Jeff]
dtype: object

#### 기타 연산자


In [310]:
names.str[0:4]

0    Woon
1     Lee
2    Stev
3    Larr
4    Elon
5    None
6    Bill
7    Mark
8    Jeff
dtype: object

In [311]:
names.str.split().str.get(-1)

0    Woong
1      Lee
2     Jobs
3     Page
4     Musk
5     None
6    Gates
7     Mark
8     Jeff
dtype: object

In [312]:
names.str.repeat(2)

0                WoongWoong
1                    LeeLee
2    Steven JobsSteven Jobs
3      Larry PageLarry Page
4        Elon MuskElon Musk
5                      None
6      Bill GatesBill Gates
7                  MarkMark
8                  JeffJeff
dtype: object

In [313]:
names.str.join('*')

0                W*o*o*n*g
1                    L*e*e
2    S*t*e*v*e*n* *J*o*b*s
3      L*a*r*r*y* *P*a*g*e
4        E*l*o*n* *M*u*s*k
5                     None
6      B*i*l*l* *G*a*t*e*s
7                  M*a*r*k
8                  J*e*f*f
dtype: object

#### 정규표현식


In [314]:
names.str.match('([A-Za-z]+)')

0    True
1    True
2    True
3    True
4    True
5    None
6    True
7    True
8    True
dtype: object

In [315]:
names.str.findall('([A-Za-z]+)')

0           [Woong]
1             [Lee]
2    [Steven, Jobs]
3     [Larry, Page]
4      [Elon, Musk]
5              None
6     [Bill, Gates]
7            [Mark]
8            [Jeff]
dtype: object

## 시계열 처리

In [319]:
idx = pd.DatetimeIndex(['2019-01-01', '2020-01-01', '2020-02-01', '2020-02-02', '2020-03-01'])
s = pd.Series([0, 1, 2, 3, 4], index=idx)
s

2019-01-01    0
2020-01-01    1
2020-02-01    2
2020-02-02    3
2020-03-01    4
dtype: int64

In [320]:
s['2020-01-01':]

2020-01-01    1
2020-02-01    2
2020-02-02    3
2020-03-01    4
dtype: int64

In [321]:
s[:'2020-01-01']

2019-01-01    0
2020-01-01    1
dtype: int64

In [322]:
s['2019']

2019-01-01    0
dtype: int64

#### 시계열 데이터 구조


In [323]:
from datetime import datetime
dates = pd.to_datetime(['12-12-2019', datetime(2020, 1, 1), '2nd of Feb, 2020', '2020-Mar-4', '20200701'])
dates

DatetimeIndex(['2019-12-12', '2020-01-01', '2020-02-02', '2020-03-04',
               '2020-07-01'],
              dtype='datetime64[ns]', freq=None)

In [324]:
dates.to_period('D')

PeriodIndex(['2019-12-12', '2020-01-01', '2020-02-02', '2020-03-04',
             '2020-07-01'],
            dtype='period[D]')

In [325]:
dates - dates[0]

TimedeltaIndex(['0 days', '20 days', '52 days', '83 days', '202 days'], dtype='timedelta64[ns]', freq=None)

In [327]:
pd.date_range('2020-01-01', '2020-07-01')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25',
               '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', length=183, freq='D')

In [328]:
pd.date_range('2020-01-01', periods=7)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')

In [329]:
pd.date_range('2020-01-01', periods=7, freq='M')

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31'],
              dtype='datetime64[ns]', freq='M')

In [330]:
pd.date_range('2020-01-01', periods=7, freq='H')

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00'],
              dtype='datetime64[ns]', freq='H')

In [331]:
idx = pd.to_datetime(['2020-01-01 12:00:00', '2020-01-02 00:00:00'] + [None])
idx

DatetimeIndex(['2020-01-01 12:00:00', '2020-01-02 00:00:00', 'NaT'], dtype='datetime64[ns]', freq=None)

In [332]:
idx[2]

NaT

In [333]:
pd.isnull(idx)

array([False, False,  True])

### 시계열 기본

In [335]:
dates = [datetime(2020, 1, 1), datetime(2020, 1, 2), datetime(2020, 1, 4), datetime(2020, 1, 7),
        datetime(2020, 1, 10), datetime(2020, 1, 11), datetime(2020, 1, 15)]
dates

[datetime.datetime(2020, 1, 1, 0, 0),
 datetime.datetime(2020, 1, 2, 0, 0),
 datetime.datetime(2020, 1, 4, 0, 0),
 datetime.datetime(2020, 1, 7, 0, 0),
 datetime.datetime(2020, 1, 10, 0, 0),
 datetime.datetime(2020, 1, 11, 0, 0),
 datetime.datetime(2020, 1, 15, 0, 0)]

In [337]:
ts = pd.Series(np.random.randn(7), index=dates)
ts

2020-01-01   -0.323609
2020-01-02    0.732223
2020-01-04   -0.719217
2020-01-07    0.436448
2020-01-10    0.522419
2020-01-11   -1.294082
2020-01-15   -0.290543
dtype: float64

In [338]:
ts.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-04', '2020-01-07',
               '2020-01-10', '2020-01-11', '2020-01-15'],
              dtype='datetime64[ns]', freq=None)

In [339]:
ts.index[0]

Timestamp('2020-01-01 00:00:00')

In [340]:
ts[ts.index[2]]

-0.7192166098423102

In [341]:
ts['20200104']

-0.7192166098423102

In [342]:
ts['1/4/2020']

-0.7192166098423102

In [345]:
ts = pd.Series(np.random.randn(1000),
                index=pd.date_range('2017-10-01', periods=1000))
ts

2017-10-01    1.870005
2017-10-02   -1.898512
2017-10-03    0.216734
2017-10-04    0.454418
2017-10-05   -0.195346
                ...   
2020-06-22   -0.450806
2020-06-23   -0.489071
2020-06-24   -0.655654
2020-06-25    0.182375
2020-06-26    1.188823
Freq: D, Length: 1000, dtype: float64

In [346]:
ts['2020']

2020-01-01   -2.613612
2020-01-02    0.395901
2020-01-03    0.525043
2020-01-04    0.509501
2020-01-05    0.418065
                ...   
2020-06-22   -0.450806
2020-06-23   -0.489071
2020-06-24   -0.655654
2020-06-25    0.182375
2020-06-26    1.188823
Freq: D, Length: 178, dtype: float64

In [347]:
ts['2020-06']

2020-06-01   -0.517763
2020-06-02   -0.386830
2020-06-03   -0.274825
2020-06-04    1.129476
2020-06-05   -0.521181
2020-06-06    1.047398
2020-06-07   -1.324421
2020-06-08   -0.643052
2020-06-09   -0.797120
2020-06-10   -1.869962
2020-06-11    1.176939
2020-06-12   -0.950394
2020-06-13   -0.415061
2020-06-14    0.580553
2020-06-15    0.350323
2020-06-16   -1.174110
2020-06-17   -0.167764
2020-06-18    0.646436
2020-06-19    1.078535
2020-06-20   -0.256058
2020-06-21    0.336755
2020-06-22   -0.450806
2020-06-23   -0.489071
2020-06-24   -0.655654
2020-06-25    0.182375
2020-06-26    1.188823
Freq: D, dtype: float64

In [348]:
ts[datetime(2020, 6, 20):]

2020-06-20   -0.256058
2020-06-21    0.336755
2020-06-22   -0.450806
2020-06-23   -0.489071
2020-06-24   -0.655654
2020-06-25    0.182375
2020-06-26    1.188823
Freq: D, dtype: float64

In [349]:
ts['2020-06-10':'2020-06-20']

2020-06-10   -1.869962
2020-06-11    1.176939
2020-06-12   -0.950394
2020-06-13   -0.415061
2020-06-14    0.580553
2020-06-15    0.350323
2020-06-16   -1.174110
2020-06-17   -0.167764
2020-06-18    0.646436
2020-06-19    1.078535
2020-06-20   -0.256058
Freq: D, dtype: float64

In [352]:
tdf = pd.DataFrame(np.random.randn(1000, 4),
                    index=pd.date_range('2017-10-01', periods=1000),
                    columns=list('ABCD'))
tdf

A         B         C         D
2017-10-01  1.049088 -0.194266  0.071072 -0.396038
2017-10-02 -0.808577  0.335096  0.044098  0.069696
2017-10-03 -1.915859 -0.101824 -0.307162  0.734383
2017-10-04  0.528826  0.942177 -0.778122  1.416348
2017-10-05 -1.788411 -0.553194 -0.284980 -0.313846
...              ...       ...       ...       ...
2020-06-22  0.241510  0.965602 -1.226448  0.242364
2020-06-23  0.103878 -0.191198 -0.091913  0.032360
2020-06-24 -1.097295 -0.123594 -0.315092  1.250740
2020-06-25 -2.067571  1.355657  0.835387 -1.027516
2020-06-26 -0.389017 -0.701425  0.904597 -0.479700

[1000 rows x 4 columns]

In [353]:
tdf['2020']

/Users/wjlee/opt/anaconda3/envs/study_ML_37/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  """Entry point for launching an IPython kernel.


A         B         C         D
2020-01-01 -0.879773  0.992752 -0.287088  2.362476
2020-01-02 -0.916994  0.061561  1.183053 -1.884933
2020-01-03 -0.211809  0.894456  0.833053  0.853531
2020-01-04  0.396635  0.555838 -1.212726 -0.928222
2020-01-05 -0.065431 -0.048705 -0.100768 -0.825750
...              ...       ...       ...       ...
2020-06-22  0.241510  0.965602 -1.226448  0.242364
2020-06-23  0.103878 -0.191198 -0.091913  0.032360
2020-06-24 -1.097295 -0.123594 -0.315092  1.250740
2020-06-25 -2.067571  1.355657  0.835387 -1.027516
2020-06-26 -0.389017 -0.701425  0.904597 -0.479700

[178 rows x 4 columns]

In [354]:
tdf.loc['2020-06']

A         B         C         D
2020-06-01 -1.385743 -0.093249  0.121579  0.096340
2020-06-02 -0.373589 -2.395020  0.002645  1.635481
2020-06-03  0.535262 -1.101628 -1.719108  1.981807
2020-06-04 -0.805583 -1.189915 -0.411945 -1.201699
2020-06-05 -0.031397 -0.597926  0.175620  0.726288
2020-06-06 -0.853305 -1.917708  0.920657  0.154248
2020-06-07  0.387032  0.282391  0.106759 -1.174564
2020-06-08  0.597332  2.115290  0.278425 -0.378636
2020-06-09  0.683272  0.654035 -0.060936 -0.646863
2020-06-10  0.311458 -0.359102  0.399004  0.002474
2020-06-11 -1.230017  0.773058  2.236325 -0.247475
2020-06-12 -0.492303  0.487615 -0.283790  0.667798
2020-06-13  1.305861  0.256267  0.903027 -1.028890
2020-06-14  0.213325  2.038397 -0.463612  1.666993
2020-06-15  0.618446 -1.502215  0.016842  0.104905
2020-06-16 -0.796271  0.162015 -0.352372  0.927136
2020-06-17 -1.269273 -0.017014 -0.613754  0.285620
2020-06-18  0.344116  1.017403  0.516942  0.193555
2020-06-19 -1.053109 -0.341399  1.418353  0.501345
2020-06-20  1.028627 -1.280837  0.591441 -0.227961
2020-06-21 -0.995244  1.859033 -1.350595  1.246099
2020-06-22  0.241510  0.965602 -1.226448  0.242364
2020-06-23  0.103878 -0.191198 -0.091913  0.032360
2020-06-24 -1.097295 -0.123594 -0.315092  1.250740
2020-06-25 -2.067571  1.355657  0.835387 -1.027516
2020-06-26 -0.389017 -0.701425  0.904597 -0.479700

In [357]:
tdf['2020-06-20':]

A         B         C         D
2020-06-20  1.028627 -1.280837  0.591441 -0.227961
2020-06-21 -0.995244  1.859033 -1.350595  1.246099
2020-06-22  0.241510  0.965602 -1.226448  0.242364
2020-06-23  0.103878 -0.191198 -0.091913  0.032360
2020-06-24 -1.097295 -0.123594 -0.315092  1.250740
2020-06-25 -2.067571  1.355657  0.835387 -1.027516
2020-06-26 -0.389017 -0.701425  0.904597 -0.479700

In [358]:
tdf['C']

2017-10-01    0.071072
2017-10-02    0.044098
2017-10-03   -0.307162
2017-10-04   -0.778122
2017-10-05   -0.284980
                ...   
2020-06-22   -1.226448
2020-06-23   -0.091913
2020-06-24   -0.315092
2020-06-25    0.835387
2020-06-26    0.904597
Freq: D, Name: C, Length: 1000, dtype: float64

In [360]:
ts = pd.Series(np.random.randn(10),
                index=pd.DatetimeIndex(['2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02' ,'2020-01-03',
                                        '2020-01-04', '2020-01-05', '2020-01-05', '2020-01-06', '2020-01-07']))
ts

2020-01-01    2.002381
2020-01-01    0.154219
2020-01-02   -0.523091
2020-01-02    0.588517
2020-01-03   -1.213323
2020-01-04    0.136450
2020-01-05    1.337919
2020-01-05   -1.322315
2020-01-06   -1.428393
2020-01-07    0.764292
dtype: float64

In [361]:
ts.index.is_unique

False

In [362]:
ts['2020-01-01']

2020-01-01    2.002381
2020-01-01    0.154219
dtype: float64

In [364]:
ts.groupby(level=0).mean()

2020-01-01    1.078300
2020-01-02    0.032713
2020-01-03   -1.213323
2020-01-04    0.136450
2020-01-05    0.007802
2020-01-06   -1.428393
2020-01-07    0.764292
dtype: float64

In [365]:
pd.date_range('2020-01-01', '2020-07-01')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25',
               '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', length=183, freq='D')

In [366]:
pd.date_range(start='2020-01-01', periods=10)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [367]:
pd.date_range(end='2020-07-01', periods=10)

DatetimeIndex(['2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25',
               '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', freq='D')

In [368]:
pd.date_range('2020-07-01', '2020-07-07', freq='B') #Business day

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-06',
               '2020-07-07'],
              dtype='datetime64[ns]', freq='B')

### 주기와 오프셋


In [369]:
pd.timedelta_range(0, periods=12, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00', '0 days 10:00:00', '0 days 11:00:00'],
               dtype='timedelta64[ns]', freq='H')

In [370]:
pd.timedelta_range(0, periods=60, freq='T')

TimedeltaIndex(['0 days 00:00:00', '0 days 00:01:00', '0 days 00:02:00',
                '0 days 00:03:00', '0 days 00:04:00', '0 days 00:05:00',
                '0 days 00:06:00', '0 days 00:07:00', '0 days 00:08:00',
                '0 days 00:09:00', '0 days 00:10:00', '0 days 00:11:00',
                '0 days 00:12:00', '0 days 00:13:00', '0 days 00:14:00',
                '0 days 00:15:00', '0 days 00:16:00', '0 days 00:17:00',
                '0 days 00:18:00', '0 days 00:19:00', '0 days 00:20:00',
                '0 days 00:21:00', '0 days 00:22:00', '0 days 00:23:00',
                '0 days 00:24:00', '0 days 00:25:00', '0 days 00:26:00',
                '0 days 00:27:00', '0 days 00:28:00', '0 days 00:29:00',
                '0 days 00:30:00', '0 days 00:31:00', '0 days 00:32:00',
                '0 days 00:33:00', '0 days 00:34:00', '0 days 00:35:00',
                '0 days 00:36:00', '0 days 00:37:00', '0 days 00:38:00',
                '0 days 00:39:00', '0 days 00:40:00

In [371]:
pd.timedelta_range(0, periods=10, freq='1H30T')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:30:00', '0 days 03:00:00',
                '0 days 04:30:00', '0 days 06:00:00', '0 days 07:30:00',
                '0 days 09:00:00', '0 days 10:30:00', '0 days 12:00:00',
                '0 days 13:30:00'],
               dtype='timedelta64[ns]', freq='90T')

In [372]:
pd.date_range('2020-01-01', periods=20, freq='B')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
               '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
               '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28'],
              dtype='datetime64[ns]', freq='B')

In [373]:
pd.date_range('2020-01-01', periods=30, freq='2H')

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 02:00:00',
               '2020-01-01 04:00:00', '2020-01-01 06:00:00',
               '2020-01-01 08:00:00', '2020-01-01 10:00:00',
               '2020-01-01 12:00:00', '2020-01-01 14:00:00',
               '2020-01-01 16:00:00', '2020-01-01 18:00:00',
               '2020-01-01 20:00:00', '2020-01-01 22:00:00',
               '2020-01-02 00:00:00', '2020-01-02 02:00:00',
               '2020-01-02 04:00:00', '2020-01-02 06:00:00',
               '2020-01-02 08:00:00', '2020-01-02 10:00:00',
               '2020-01-02 12:00:00', '2020-01-02 14:00:00',
               '2020-01-02 16:00:00', '2020-01-02 18:00:00',
               '2020-01-02 20:00:00', '2020-01-02 22:00:00',
               '2020-01-03 00:00:00', '2020-01-03 02:00:00',
               '2020-01-03 04:00:00', '2020-01-03 06:00:00',
               '2020-01-03 08:00:00', '2020-01-03 10:00:00'],
              dtype='datetime64[ns]', freq='2H')

In [374]:
pd.date_range('2020-01-01', periods=20, freq='S')

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 00:00:01',
               '2020-01-01 00:00:02', '2020-01-01 00:00:03',
               '2020-01-01 00:00:04', '2020-01-01 00:00:05',
               '2020-01-01 00:00:06', '2020-01-01 00:00:07',
               '2020-01-01 00:00:08', '2020-01-01 00:00:09',
               '2020-01-01 00:00:10', '2020-01-01 00:00:11',
               '2020-01-01 00:00:12', '2020-01-01 00:00:13',
               '2020-01-01 00:00:14', '2020-01-01 00:00:15',
               '2020-01-01 00:00:16', '2020-01-01 00:00:17',
               '2020-01-01 00:00:18', '2020-01-01 00:00:19'],
              dtype='datetime64[ns]', freq='S')

### 시프트(Shift)

In [375]:
ts = pd.Series(np.random.randn(5),
                index=pd.date_range('2020-01-01', periods=5, freq='B'))
ts

2020-01-01    1.188142
2020-01-02   -1.011970
2020-01-03    0.221574
2020-01-06   -0.321387
2020-01-07    0.602209
Freq: B, dtype: float64

In [376]:
ts.shift(1)

2020-01-01         NaN
2020-01-02    1.188142
2020-01-03   -1.011970
2020-01-06    0.221574
2020-01-07   -0.321387
Freq: B, dtype: float64

In [377]:
ts.shift(3)

2020-01-01         NaN
2020-01-02         NaN
2020-01-03         NaN
2020-01-06    1.188142
2020-01-07   -1.011970
Freq: B, dtype: float64

In [378]:
ts.shift(-1)

2020-01-01   -1.011970
2020-01-02    0.221574
2020-01-03   -0.321387
2020-01-06    0.602209
2020-01-07         NaN
Freq: B, dtype: float64

In [379]:
ts.shift(3, freq='B')

2020-01-06    1.188142
2020-01-07   -1.011970
2020-01-08    0.221574
2020-01-09   -0.321387
2020-01-10    0.602209
Freq: B, dtype: float64

In [380]:
ts.shift(2, freq='W')

2020-01-12    1.188142
2020-01-12   -1.011970
2020-01-12    0.221574
2020-01-19   -0.321387
2020-01-19    0.602209
dtype: float64

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

In [381]:
import pytz
pytz.common_timezones

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'Amer

In [382]:
tz = pytz.timezone('Asia/Seoul')

In [383]:
dinx = pd.date_range('2020-01-01 09:00', periods=7, freq='B')
ts = pd.Series(np.random.randn(len(dinx)), index=dinx)
ts

2020-01-01 09:00:00   -0.231974
2020-01-02 09:00:00    0.944886
2020-01-03 09:00:00   -1.401937
2020-01-06 09:00:00   -1.879838
2020-01-07 09:00:00   -1.992368
2020-01-08 09:00:00    0.929822
2020-01-09 09:00:00   -1.571033
Freq: B, dtype: float64

In [384]:
pd.date_range('2020-01-01 09:00', periods=7, freq='B', tz='UTC')

DatetimeIndex(['2020-01-01 09:00:00+00:00', '2020-01-02 09:00:00+00:00',
               '2020-01-03 09:00:00+00:00', '2020-01-06 09:00:00+00:00',
               '2020-01-07 09:00:00+00:00', '2020-01-08 09:00:00+00:00',
               '2020-01-09 09:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

In [385]:
ts_utc = ts.tz_localize('UTC')
ts_utc

2020-01-01 09:00:00+00:00   -0.231974
2020-01-02 09:00:00+00:00    0.944886
2020-01-03 09:00:00+00:00   -1.401937
2020-01-06 09:00:00+00:00   -1.879838
2020-01-07 09:00:00+00:00   -1.992368
2020-01-08 09:00:00+00:00    0.929822
2020-01-09 09:00:00+00:00   -1.571033
Freq: B, dtype: float64

In [386]:
ts_utc.index

DatetimeIndex(['2020-01-01 09:00:00+00:00', '2020-01-02 09:00:00+00:00',
               '2020-01-03 09:00:00+00:00', '2020-01-06 09:00:00+00:00',
               '2020-01-07 09:00:00+00:00', '2020-01-08 09:00:00+00:00',
               '2020-01-09 09:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

In [387]:
ts_utc.tz_convert('Asia/Seoul')

2020-01-01 18:00:00+09:00   -0.231974
2020-01-02 18:00:00+09:00    0.944886
2020-01-03 18:00:00+09:00   -1.401937
2020-01-06 18:00:00+09:00   -1.879838
2020-01-07 18:00:00+09:00   -1.992368
2020-01-08 18:00:00+09:00    0.929822
2020-01-09 18:00:00+09:00   -1.571033
Freq: B, dtype: float64

In [388]:
ts_seoul = ts.tz_localize('Asia/Seoul')
ts_seoul

2020-01-01 09:00:00+09:00   -0.231974
2020-01-02 09:00:00+09:00    0.944886
2020-01-03 09:00:00+09:00   -1.401937
2020-01-06 09:00:00+09:00   -1.879838
2020-01-07 09:00:00+09:00   -1.992368
2020-01-08 09:00:00+09:00    0.929822
2020-01-09 09:00:00+09:00   -1.571033
dtype: float64

In [389]:
ts_seoul.tz_convert('UTC')

2020-01-01 00:00:00+00:00   -0.231974
2020-01-02 00:00:00+00:00    0.944886
2020-01-03 00:00:00+00:00   -1.401937
2020-01-06 00:00:00+00:00   -1.879838
2020-01-07 00:00:00+00:00   -1.992368
2020-01-08 00:00:00+00:00    0.929822
2020-01-09 00:00:00+00:00   -1.571033
dtype: float64

In [390]:
ts_seoul.tz_convert('Europe/Berlin')

2020-01-01 01:00:00+01:00   -0.231974
2020-01-02 01:00:00+01:00    0.944886
2020-01-03 01:00:00+01:00   -1.401937
2020-01-06 01:00:00+01:00   -1.879838
2020-01-07 01:00:00+01:00   -1.992368
2020-01-08 01:00:00+01:00    0.929822
2020-01-09 01:00:00+01:00   -1.571033
dtype: float64

In [391]:
ts.index.tz_localize('America/New_York')

DatetimeIndex(['2020-01-01 09:00:00-05:00', '2020-01-02 09:00:00-05:00',
               '2020-01-03 09:00:00-05:00', '2020-01-06 09:00:00-05:00',
               '2020-01-07 09:00:00-05:00', '2020-01-08 09:00:00-05:00',
               '2020-01-09 09:00:00-05:00'],
              dtype='datetime64[ns, America/New_York]', freq=None)

In [395]:
stamp = pd.Timestamp('2020-01-01 12:00')
stamp_utc = stamp.tz_localize('UTC')
stamp_utc

Timestamp('2020-01-01 12:00:00+0000', tz='UTC')

In [393]:
stamp_utc.value

1577880000000000000

In [394]:
stamp_utc.tz_convert('Asia/Seoul')

Timestamp('2020-01-01 21:00:00+0900', tz='Asia/Seoul')

In [396]:
stamp_utc.tz_convert('Asia/Seoul').value

1577880000000000000

In [397]:
stamp_ny = pd.Timestamp('2020-01-01 12:00', tz='America/New_York')
stamp_ny

Timestamp('2020-01-01 12:00:00-0500', tz='America/New_York')

In [400]:
stamp_ny.value

1577898000000000000

In [401]:
stamp_utc.tz_convert('Asia/Shanghai')

Timestamp('2020-01-01 20:00:00+0800', tz='Asia/Shanghai')

In [402]:
stmap = pd.Timestamp('2020-01-01 12:00', tz='Asia/Seoul')
stamp

Timestamp('2020-01-01 12:00:00')

In [403]:
from pandas.tseries.offsets import Hour
stamp + Hour()

Timestamp('2020-01-01 13:00:00')

In [404]:
stamp + 3 * Hour()

Timestamp('2020-01-01 15:00:00')

In [405]:
ts_utc

2020-01-01 09:00:00+00:00   -0.231974
2020-01-02 09:00:00+00:00    0.944886
2020-01-03 09:00:00+00:00   -1.401937
2020-01-06 09:00:00+00:00   -1.879838
2020-01-07 09:00:00+00:00   -1.992368
2020-01-08 09:00:00+00:00    0.929822
2020-01-09 09:00:00+00:00   -1.571033
Freq: B, dtype: float64

In [407]:
ts1 = ts_utc[:5].tz_convert('Europe/Berlin')
ts2 = ts_utc[2:].tz_convert('America/New_York')
ts = ts1 + ts2

In [408]:
ts.index

DatetimeIndex(['2020-01-01 09:00:00+00:00', '2020-01-02 09:00:00+00:00',
               '2020-01-03 09:00:00+00:00', '2020-01-06 09:00:00+00:00',
               '2020-01-07 09:00:00+00:00', '2020-01-08 09:00:00+00:00',
               '2020-01-09 09:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

### 기간과 기간 연산

In [409]:
p = pd.Period(2020, freq='A-JAN')
p

Period('2020', 'A-JAN')

In [410]:
p + 2

Period('2022', 'A-JAN')

In [411]:
p - 3

Period('2017', 'A-JAN')

In [413]:
p1 = pd.Period(2010, freq='A-JAN')
p2 = pd.Period(2020, freq='A-JAN')
p2 - p1

<10 * YearEnds: month=1>

In [414]:
pr = pd.period_range('2020-01-01', '2020-06-30', freq='M')

In [415]:
pd.Series(np.random.randn(6), index=pr)

2020-01   -0.089248
2020-02    0.526188
2020-03    0.363866
2020-04   -0.124399
2020-05   -0.324246
2020-06   -0.373334
Freq: M, dtype: float64

In [416]:
pidx = pd.PeriodIndex(['2020-1', '2020-1', '2020-4'], freq='M')
pidx

PeriodIndex(['2020-01', '2020-01', '2020-04'], dtype='period[M]')

In [417]:
p = pd.Period('2020', freq='A-FEB')
p

Period('2020', 'A-FEB')

In [418]:
p.asfreq('M', how='start')

Period('2019-03', 'M')

In [419]:
p.asfreq('M', how='end')

Period('2020-02', 'M')

In [420]:
p = pd.Period('2020', freq='A-OCT')
p

Period('2020', 'A-OCT')

In [421]:
p.asfreq('M', how='start')

Period('2019-11', 'M')

In [422]:
p.asfreq('M', how='end')

Period('2020-10', 'M')

In [423]:
pr = pd.period_range('2010', '2020', freq='A-JAN')
ts = pd.Series(np.random.randn(len(pr)), index=pr)
ts

2010    0.696913
2011    0.676093
2012    2.099618
2013   -0.582205
2014    0.518523
2015    0.356955
2016    0.071253
2017    0.483859
2018   -0.286389
2019   -1.192304
2020   -1.339436
Freq: A-JAN, dtype: float64

In [424]:
ts.asfreq('M', how='start')

2009-02    0.696913
2010-02    0.676093
2011-02    2.099618
2012-02   -0.582205
2013-02    0.518523
2014-02    0.356955
2015-02    0.071253
2016-02    0.483859
2017-02   -0.286389
2018-02   -1.192304
2019-02   -1.339436
Freq: M, dtype: float64

In [425]:
ts.asfreq('B', how='end')

2010-01-29    0.696913
2011-01-31    0.676093
2012-01-31    2.099618
2013-01-31   -0.582205
2014-01-31    0.518523
2015-01-30    0.356955
2016-01-29    0.071253
2017-01-31    0.483859
2018-01-31   -0.286389
2019-01-31   -1.192304
2020-01-31   -1.339436
Freq: B, dtype: float64

In [426]:
p = pd.Period('2020Q2', freq='Q-JAN')
p

Period('2020Q2', 'Q-JAN')

In [427]:
p.asfreq('D', 'start')

Period('2019-05-01', 'D')

In [428]:
p.asfreq('D', 'end')

Period('2019-07-31', 'D')

In [429]:
pr = pd.period_range('2019Q3', '2020Q3', freq='Q-JAN')
ts = pd.Series(np.random.randn(len(pr)), index=pr)
ts

2019Q3   -1.241992
2019Q4   -0.048622
2020Q1   -2.260985
2020Q2    0.843829
2020Q3   -0.484396
Freq: Q-JAN, dtype: float64

In [432]:
pr = pd.date_range('2020-01-01', periods=5, freq='Q-JAN')
ts = pd.Series(np.random.randn(5), index=pr)
ts

2020-01-31    1.113880
2020-04-30   -0.899666
2020-07-31    0.015912
2020-10-31   -1.247704
2021-01-31   -1.258393
Freq: Q-JAN, dtype: float64

In [433]:
ts.to_period()

2020Q4    1.113880
2021Q1   -0.899666
2021Q2    0.015912
2021Q3   -1.247704
2021Q4   -1.258393
Freq: Q-JAN, dtype: float64

In [434]:
pr = pd.date_range('2020-01-01', periods=5, freq='D')
ts = pd.Series(np.random.randn(5), index=pr)
ts

2020-01-01   -0.913591
2020-01-02    0.413957
2020-01-03   -0.376334
2020-01-04   -1.348413
2020-01-05   -1.976274
Freq: D, dtype: float64

In [435]:
p = ts.to_period('M')
p

2020-01   -0.913591
2020-01    0.413957
2020-01   -0.376334
2020-01   -1.348413
2020-01   -1.976274
Freq: M, dtype: float64

In [436]:
p.to_timestamp(how='start')

2020-01-01   -0.913591
2020-01-01    0.413957
2020-01-01   -0.376334
2020-01-01   -1.348413
2020-01-01   -1.976274
dtype: float64

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly