<a href="https://colab.research.google.com/github/wjlee611/studyPython_Library/blob/main/_NumPy_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__

'1.21.2'



---



## 배열 생성

### 리스트로 배열 만들기


In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 3 4 5]


In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [4]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [6]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [7]:
np.full((3, 3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [9]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [10]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [11]:
print(a1)
np.zeros_like(a1)

[4 5 3 4 5]


array([0, 0, 0, 0, 0])

In [12]:
print(a2)
np.full_like(a2, 0.01)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
print(a3)
np.empty_like(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[   0, 2043,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [14]:
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [16]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [17]:
np.random.random((3, 3))

array([[0.25467612, 0.68582637, 0.11035426],
       [0.12506301, 0.96623594, 0.97252206],
       [0.38437746, 0.00442662, 0.35053452]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [18]:
np.random.randint(0, 10, (3, 3))

array([[3, 1, 8],
       [9, 9, 7],
       [4, 9, 8]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [19]:
np.random.normal(0, 1, (3, 3))

array([[-1.69439302,  1.01621519,  0.21726689],
       [ 1.90006241, -2.11312543,  0.04970945],
       [-0.04226157,  0.1640513 , -0.26914185]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.rand(3, 3)

array([[0.46776116, 0.3545587 , 0.01584942],
       [0.28800593, 0.62713414, 0.39766951],
       [0.65225295, 0.25523184, 0.51856602]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.randn(3, 3)

array([[ 0.14207253, -0.18648963,  2.65258326],
       [-0.50175214, -0.8682768 ,  0.40708209],
       [-0.60286462, -2.02617983, -0.42427876]])

### 표준 데이터 타입

In [22]:
np.zeros(20, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.full((3, 3), 1.23, dtype = float)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

### 날짜/시간 배열 생성


In [25]:
date = np.array('2022-02-24', dtype=np.datetime64)
date

array('2022-02-24', dtype='datetime64[D]')

In [26]:
date + np.arange(12)

array(['2022-02-24', '2022-02-25', '2022-02-26', '2022-02-27',
       '2022-02-28', '2022-03-01', '2022-03-02', '2022-03-03',
       '2022-03-04', '2022-03-05', '2022-03-06', '2022-03-07'],
      dtype='datetime64[D]')

In [27]:
datetime = np.datetime64('2022-02-24 16:00')
datetime

numpy.datetime64('2022-02-24T16:00')

In [28]:
datetime = np.datetime64('2022-02-24 16:00:50.12', 'ns')
datetime

numpy.datetime64('2022-02-24T16:00:50.120000000')



---



## 배열 조회

### 배열 속성 정보

In [29]:
def array_info(array):
    print(array)
    print('ndim:', array.ndim)
    print('shape:', array.shape)
    print('dtype:', array.dtype)
    print('size:', array.size)
    print('itemsize:', array.itemsize)
    print('nbytes:', array.nbytes)
    print('strides:', array.strides)

In [30]:
array_info(a1)

[4 5 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [31]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [32]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


```strides()```: 다음 차원으로 넘어가기 위해 필요한 자원(bytes)

### 인덱싱(Indexing)

In [33]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[-1])
print(a1[-2])

[4 5 3 4 5]
4
5
5
4


In [34]:
print(a2)
print(a2[0, 0])
print(a2[0, 1])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
5
9


In [35]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [36]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 3 4 5]
[4 5]
[4 5 3 4 5]
[4]
[4 3 5]
[5 4 3 5 4]


In [37]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [38]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 3 4 5]
[5 3 5]
[4 3 4]


In [39]:
print(a2)
bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False  True  True]
 [False  True False]]
[5 6 8]


### 팬시 인덱싱(Fancy Indedxing)

In [40]:
print(a1)
print([a1[0], a1[2]])
idx = [0, 2]
print(a1[idx])
idx = np.array([[0, 1],
                [2, 0]])
print(a1[idx])

[4 5 3 4 5]
[4, 3]
[4 3]
[[4 5]
 [3 4]]


In [41]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [42]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 3 4 5]
[10  4  5  3  4  5]
[4 5 3 4 5]
[ 4  5 10  3  4  5]


In [43]:
print(a2)
b2 = np.insert(a2, 1, [10, 11, 12], axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [44]:
print(a1)
a1[0] = 1
a1[1] = 2
print(a1)
a1[:2] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 3 4 5]
[1 2 3 4 5]
[9 9 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [45]:
print(a2)
a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
print(a2)
a2[0] = 1
print(a2)
a2[1:, 2] = 9
print(a2)
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [46]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [47]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [48]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [49]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [50]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [51]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [52]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [53]:
print(a3)
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [54]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [55]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [56]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize(5, 2)
print(n2)

[[4 4 5 9 5]
 [8 2 1 2 1]]
[[4 4]
 [5 9]
 [5 8]
 [2 1]
 [2 1]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [57]:
n2.resize(5, 5)
print(n2)

[[4 4 5 9 5]
 [8 2 1 2 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [58]:
n2.resize(3, 3)
print(n2)

[[4 4 5]
 [9 5 8]
 [2 1 2]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [59]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [60]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [61]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [62]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [63]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [64]:
c1 = np.array([7,8,9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [65]:
a2 = np.array([[1,2,3], 
                [4,5,6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [67]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [68]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [69]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [70]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [71]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [72]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [73]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [74]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [75]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

[1 2 3]
[6 7 8]


In [76]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1+a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [77]:
b2 = np.array([1,2,3]).reshape(3, 1)
print(b2)
print(a1+b2)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [78]:
a1 = np.arange(1, 10)
print(a1)
print(a1+1)
print(np.add(a1, 10))
print(a1-2)
print(np.subtract(a1, 10))
print(-a1)
print(np.negative(a1))
print(a1*2)
print(np.multiply(a1, 2))
print(np.divide(a1, 2))  # /
print(np.floor_divide(a1, 2))  # //: 나누고 내림
print(np.power(a1, 2))  # **
print(np.mod(a1, 2))  # %

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]


In [79]:
a1 = np.arange(1, 10)
b1 = np.random.randint(1, 10, size=9)
print(a1)
print(b1)
print(a1+b1)
print(a1*b1)
print(a1//b1)
print(a1**b1)
print(a1%b1)

[1 2 3 4 5 6 7 8 9]
[5 9 1 6 4 2 2 2 9]
[ 6 11  4 10  9  8  9 10 18]
[ 5 18  3 24 20 12 14 16 81]
[0 0 3 0 1 3 3 4 1]
[        1       512         3      4096       625        36        49
        64 387420489]
[1 2 0 4 1 0 1 0 0]


In [80]:
a2 = np.arange(1, 10).reshape(3, 3)
b2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(b2)
print(a2+b2)
print(a2*b2)
print(a2//b2)
print(a2**b2)
print(a2%b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 8 1]
 [7 7 6]
 [7 3 9]]
[[ 3 10  4]
 [11 12 12]
 [14 11 18]]
[[ 2 16  3]
 [28 35 36]
 [49 24 81]]
[[0 0 3]
 [0 0 1]
 [1 2 1]]
[[        1       256         3]
 [    16384     78125     46656]
 [   823543       512 387420489]]
[[1 2 0]
 [4 5 0]
 [0 2 0]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [81]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 3  1 -2  2  9]
[3 1 2 2 9]
[3 1 2 2 9]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [82]:
print(a2)
print(np.square(a2))
print(np.sqrt(a2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


#### 지수와 로그 함수 (Exponential and Log Function)

In [83]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[7 7 4 8 1]
[1.09663316e+03 1.09663316e+03 5.45981500e+01 2.98095799e+03
 2.71828183e+00]
[128. 128.  16. 256.   2.]
[49 49 16 64  1]


In [84]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 7 4 8 1]
[1.94591015 1.94591015 1.38629436 2.07944154 0.        ]
[2.80735492 2.80735492 2.         3.         0.        ]
[0.84509804 0.84509804 0.60205999 0.90308999 0.        ]


#### 삼각 함수(Trigonometrical Function)


In [85]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [86]:
x = [-1, 0 ,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [87]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
38 38
[12 12 14] [12 12 14]
[ 6 22 10] [ 6 22 10]


#### cumsum(): 누적합 계산

In [88]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
[ 1  2  6 14 20 28 31 36 38]
[[ 1  1  4]
 [ 9  7 12]
 [12 12 14]]
[[ 1  2  6]
 [ 8 14 22]
 [ 3  8 10]]


#### diff(): 차분 계산

In [89]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
[[ 0  3]
 [-2  2]
 [ 2 -3]]
[[ 7  5  4]
 [-5 -1 -6]]
[[ 0  3]
 [-2  2]
 [ 2 -3]]


#### prod(): 곱 계산

In [90]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
46080
[24 30 64]
[  4 384  30]


#### cumprod(): 누적곱 계산

In [91]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
[    1     1     4    32   192  1536  4608 23040 46080]
[[ 1  1  4]
 [ 8  6 32]
 [24 30 64]]
[[  1   1   4]
 [  8  48 384]
 [  3  15  30]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [92]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 6  6  6]
 [22 22 22]
 [10 10 10]]
[[ 6  6  6]
 [22 22 22]
 [10 10 10]]


#### tensordot(): 텐서곱 계산

In [93]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
38
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]]
[[ 6  6  6]
 [22 22 22]
 [10 10 10]]


#### cross(): 벡터곱

In [94]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [95]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 6  6  6]
 [22 22 22]
 [10 10 10]]
[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [4 4 4 4 4 4 4 4 4]
 [8 8 8 8 8 8 8 8 8]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2]]


#### mean(): 평균 계산

In [96]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
4.222222222222222
[4.         4.         4.66666667]
[2.         7.33333333 3.33333333]


#### std(): 표준 편차 계산

In [97]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
2.57240820062005
[2.94392029 2.1602469  2.49443826]
[1.41421356 0.94280904 1.24721913]


#### var(): 분산 계산

In [98]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
6.617283950617283
[8.66666667 4.66666667 6.22222222]
[2.         0.88888889 1.55555556]


#### min(): 최소값

In [99]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
1
[1 1 2]
[1 6 2]


#### max(): 최대값

In [100]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
8
[8 6 8]
[4 8 5]


#### argmin(): 최소값 인덱스

In [101]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
0
[0 0 2]
[0 1 2]


#### argmax(): 최대값 인덱스

In [102]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
3
[1 1 1]
[2 0 1]


#### median(): 중앙값

In [103]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[1 1 4]
 [8 6 8]
 [3 5 2]]
4.0
[3. 5. 4.]
[1. 8. 3.]


#### percentile(): 백분위 수



In [104]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [105]:
a2 = np.array([[False, False, True],
                [False, True, True],
                [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False  True]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[ True  True  True]


#### all()

In [106]:
a2 = np.array([[False, False, True],
                [False, True, True],
                [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [False  True  True]
 [False  True  True]]
False
[False False  True]
[False False False]


### 비교 연산(Comparison Operators)


In [107]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [108]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [109]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [110]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [111]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [112]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[8 2 9 1 3 1 4 9 7 4]
[1 1 2 3 4 4 7 8 9 9]
[8 2 9 1 3 1 4 9 7 4]
[3 5 1 4 6 9 8 0 2 7]
[8 2 9 1 3 1 4 9 7 4]
None
[1 1 2 3 4 4 7 8 9 9]


In [113]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[3 9 4]
 [5 7 9]
 [4 3 1]]
[[3 3 1]
 [4 7 4]
 [5 9 9]]
[[3 4 9]
 [5 7 9]
 [1 3 4]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [114]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[4 7 2 6 6 5 9 6 3 1]
[3 1 2 4 7 5 9 6 6 6]


In [115]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[5 8 5 9 2]
 [1 9 8 8 7]
 [4 3 9 2 9]
 [2 7 1 8 2]
 [1 6 3 3 6]]
[[2 5 5 8 9]
 [1 7 8 8 9]
 [2 4 3 9 9]
 [1 2 2 7 8]
 [3 1 3 6 6]]
[[2 3 1 2 2]
 [1 6 3 3 2]
 [1 7 5 8 6]
 [4 8 8 8 7]
 [5 9 9 9 9]]
[[2 5 5 8 9]
 [1 7 8 8 9]
 [2 4 3 9 9]
 [1 2 2 7 8]
 [3 1 3 6 6]]


## 배열 입출력


In [116]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save('a', a2)

[[4 2 1 1 1]
 [5 4 4 3 5]
 [5 5 9 8 7]
 [9 9 5 9 8]
 [5 4 7 6 8]]


In [117]:
!ls

_NumPy_한번에_제대로_배우기.ipynb
a.csv
a.npy
ab.npz
b.csv


In [118]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez('ab', a2, b2)

[[7 1 1 8 2]
 [1 9 7 6 1]
 [1 6 5 6 9]
 [3 3 5 5 9]
 [3 3 1 7 5]]


In [119]:
!ls

_NumPy_한번에_제대로_배우기.ipynb
a.csv
a.npy
ab.npz
b.csv


In [120]:
npy = np.load('a.npy')
print(npy)

[[4 2 1 1 1]
 [5 4 4 3 5]
 [5 5 9 8 7]
 [9 9 5 9 8]
 [5 4 7 6 8]]


In [121]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[4 2 1 1 1]
 [5 4 4 3 5]
 [5 5 9 8 7]
 [9 9 5 9 8]
 [5 4 7 6 8]]
[[7 1 1 8 2]
 [1 9 7 6 1]
 [1 6 5 6 9]
 [3 3 5 5 9]
 [3 3 1 7 5]]


In [122]:
print(a2)
np.savetxt('a.csv', a2, delimiter=',')

[[4 2 1 1 1]
 [5 4 4 3 5]
 [5 5 9 8 7]
 [9 9 5 9 8]
 [5 4 7 6 8]]


In [123]:
!ls

_NumPy_한번에_제대로_배우기.ipynb
a.csv
a.npy
ab.npz
b.csv


In [124]:
!cat a.csv

4.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00,1.000000000000000000e+00,1.000000000000000000e+00
5.000000000000000000e+00,4.000000000000000000e+00,4.000000000000000000e+00,3.000000000000000000e+00,5.000000000000000000e+00
5.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00,8.000000000000000000e+00,7.000000000000000000e+00
9.000000000000000000e+00,9.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00,8.000000000000000000e+00
5.000000000000000000e+00,4.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00


In [125]:
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[[4. 2. 1. 1. 1.]
 [5. 4. 4. 3. 5.]
 [5. 5. 9. 8. 7.]
 [9. 9. 5. 9. 8.]
 [5. 4. 7. 6. 8.]]


In [126]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5', )

[[7 1 1 8 2]
 [1 9 7 6 1]
 [1 6 5 6 9]
 [3 3 5 5 9]
 [3 3 1 7 5]]


In [127]:
!cat b.csv

# c1, c2, c3, c4, c5
7.00e+00,1.00e+00,1.00e+00,8.00e+00,2.00e+00
1.00e+00,9.00e+00,7.00e+00,6.00e+00,1.00e+00
1.00e+00,6.00e+00,5.00e+00,6.00e+00,9.00e+00
3.00e+00,3.00e+00,5.00e+00,5.00e+00,9.00e+00
3.00e+00,3.00e+00,1.00e+00,7.00e+00,5.00e+00


In [128]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[7. 1. 1. 8. 2.]
 [1. 9. 7. 6. 1.]
 [1. 6. 5. 6. 9.]
 [3. 3. 5. 5. 9.]
 [3. 3. 1. 7. 5.]]




---

